// app/automotive/data.ts

export interface Car {
  id: string;
  name: string;
  manufacturer: string;
  year: string;
  class: string;
  specs: {
    engine: string;
    power: string;
    torque: string;
    weight: string;
    acceleration: string;
    topSpeed: string;
    drivetrain: string;
  };
  history: string;
  image: string;
  searchQuery?: string;
  accentColor: string;
}

export const CARS: Car[] = [
  // ====================== ZENITH (The 1-of-5) ======================
  {
    id: '919-hybrid-evo', name: '919 Hybrid Evo', manufacturer: 'Porsche', year: '2018', class: 'Le Mans Prototype',
    specs: { engine: '2.0L V4 Turbo + Hybrid', power: '1,160 hp', torque: 'Unknown', weight: '849 kg', acceleration: '2.2s', topSpeed: '369 km/h', drivetrain: 'AWD' },
    history: 'The Nürburgring King (5:19.546). Only 5 of these cards exist in the entire game.',
    image: '', searchQuery: 'Porsche 919 Hybrid Evo', accentColor: '#525252'
  },

  // ====================== ULTRA (Hypercars / F1) ======================
  { id: 'mp4-4', name: 'MP4/4', manufacturer: 'McLaren', year: '1988', class: 'Formula 1', specs: { engine: '1.5L V6 Turbo', power: '650+ hp', torque: 'N/A', weight: '540 kg', acceleration: '2.5s', topSpeed: '330 km/h', drivetrain: 'RWD' }, history: 'Senna\'s championship car.', image: '', accentColor: '#ef4444' },
  { id: 'f2004', name: 'F2004', manufacturer: 'Ferrari', year: '2004', class: 'Formula 1', specs: { engine: '3.0L V10', power: '900+ hp', torque: 'N/A', weight: '605 kg', acceleration: '2.0s', topSpeed: '360 km/h', drivetrain: 'RWD' }, history: 'The peak of the V10 era.', image: '', accentColor: '#dc2626' },
  { id: 'w11', name: 'W11 EQ Performance', manufacturer: 'Mercedes-AMG', year: '2020', class: 'Formula 1', specs: { engine: '1.6L V6 Hybrid', power: '1000+ hp', torque: 'N/A', weight: '746 kg', acceleration: '2.3s', topSpeed: '350 km/h', drivetrain: 'RWD' }, history: 'The fastest F1 car ever over one lap.', image: '', accentColor: '#00d2be' },
  { id: '787b', name: '787B', manufacturer: 'Mazda', year: '1991', class: 'Le Mans Prototype', specs: { engine: 'R26B 4-Rotor', power: '700 hp', torque: '608 Nm', weight: '830 kg', acceleration: '2.9s', topSpeed: '340 km/h', drivetrain: 'RWD' }, history: 'The screaming rotary Le Mans winner.', image: '', accentColor: '#f97316' },
  { id: 'sauber-c9', name: 'Sauber C9', manufacturer: 'Mercedes-Benz', year: '1989', class: 'Le Mans Prototype', specs: { engine: '5.0L V8 TT', power: '720 hp', torque: '810 Nm', weight: '900 kg', acceleration: '2.8s', topSpeed: '400 km/h', drivetrain: 'RWD' }, history: 'Hit 400km/h on the Mulsanne Straight.', image: '', accentColor: '#d4d4d8' },
  { id: 'mclaren-f1', name: 'F1', manufacturer: 'McLaren', year: '1993', class: 'Hypercar', specs: { engine: '6.1L V12', power: '627 hp', torque: '650 Nm', weight: '1,138 kg', acceleration: '3.2s', topSpeed: '386 km/h', drivetrain: 'RWD' }, history: 'The greatest supercar ever made.', image: '', accentColor: '#ea580c' },
  { id: 'mclaren-f1-lm', name: 'F1 LM', manufacturer: 'McLaren', year: '1995', class: 'Hypercar', specs: { engine: '6.1L V12', power: '680 hp', torque: '705 Nm', weight: '1,062 kg', acceleration: '2.9s', topSpeed: '362 km/h', drivetrain: 'RWD' }, history: 'Papaya Orange tribute to Le Mans.', image: '', accentColor: '#f97316' },
  { id: 'veyron-ss', name: 'Veyron Super Sport', manufacturer: 'Bugatti', year: '2010', class: 'Hypercar', specs: { engine: '8.0L W16', power: '1200 hp', torque: '1500 Nm', weight: '1888 kg', acceleration: '2.5s', topSpeed: '431 km/h', drivetrain: 'AWD' }, history: 'First to break 430km/h.', image: '', accentColor: '#000000' },
  { id: 'chiron-ss', name: 'Chiron Super Sport', manufacturer: 'Bugatti', year: '2020', class: 'Hypercar', specs: { engine: '8.0L W16', power: '1600 hp', torque: '1600 Nm', weight: '1978 kg', acceleration: '2.4s', topSpeed: '490 km/h', drivetrain: 'AWD' }, history: 'The 300mph barrier breaker.', image: '', accentColor: '#ea580c' },
  { id: 'jesko', name: 'Jesko Absolut', manufacturer: 'Koenigsegg', year: '2022', class: 'Hypercar', specs: { engine: '5.0L V8 TT', power: '1600 hp', torque: '1500 Nm', weight: '1320 kg', acceleration: '2.5s', topSpeed: '530 km/h', drivetrain: 'RWD' }, history: 'Fastest Koenigsegg forever.', image: '', accentColor: '#9ca3af' },
  { id: 'one-1', name: 'One:1', manufacturer: 'Koenigsegg', year: '2014', class: 'Hypercar', specs: { engine: '5.0L V8 TT', power: '1360 hp', torque: '1371 Nm', weight: '1360 kg', acceleration: '2.8s', topSpeed: '440 km/h', drivetrain: 'RWD' }, history: 'The world\'s first Megacar.', image: '', accentColor: '#d4d4d8' },
  { id: 'valkyrie', name: 'Valkyrie', manufacturer: 'Aston Martin', year: '2021', class: 'Hypercar', specs: { engine: '6.5L V12', power: '1160 hp', torque: '900 Nm', weight: '1030 kg', acceleration: '2.5s', topSpeed: '400 km/h', drivetrain: 'RWD' }, history: 'F1 car for the road.', image: '', accentColor: '#047857' },
  { id: 'amg-one', name: 'AMG One', manufacturer: 'Mercedes-AMG', year: '2022', class: 'Hypercar', specs: { engine: '1.6L V6 Turbo Hybrid', power: '1063 hp', torque: 'Unknown', weight: '1695 kg', acceleration: '2.9s', topSpeed: '352 km/h', drivetrain: 'AWD' }, history: 'Literally an F1 engine.', image: '', accentColor: '#d4d4d8' },
  { id: 'laferrari', name: 'LaFerrari', manufacturer: 'Ferrari', year: '2013', class: 'Hypercar', specs: { engine: '6.3L V12 Hybrid', power: '950 hp', torque: '900 Nm', weight: '1255 kg', acceleration: '2.4s', topSpeed: '350 km/h', drivetrain: 'RWD' }, history: 'The definitive hybrid Ferrari.', image: '', accentColor: '#dc2626' },
  { id: 'p1', name: 'P1', manufacturer: 'McLaren', year: '2013', class: 'Hypercar', specs: { engine: '3.8L V8 Hybrid', power: '903 hp', torque: '900 Nm', weight: '1395 kg', acceleration: '2.8s', topSpeed: '350 km/h', drivetrain: 'RWD' }, history: 'The widowmaker.', image: '', accentColor: '#facc15' },
  { id: '918', name: '918 Spyder', manufacturer: 'Porsche', year: '2013', class: 'Hypercar', specs: { engine: '4.6L V8 Hybrid', power: '887 hp', torque: '1280 Nm', weight: '1634 kg', acceleration: '2.6s', topSpeed: '345 km/h', drivetrain: 'AWD' }, history: 'Sub-7 minute master.', image: '', accentColor: '#a1a1aa' },
  { id: 'zonda-r', name: 'Zonda R', manufacturer: 'Pagani', year: '2009', class: 'Hypercar', specs: { engine: '6.0L V12', power: '740 hp', torque: '710 Nm', weight: '1070 kg', acceleration: '2.7s', topSpeed: '350 km/h', drivetrain: 'RWD' }, history: 'Track-only laboratory.', image: '', accentColor: '#000000' },
  { id: 'huayra-r', name: 'Huayra R', manufacturer: 'Pagani', year: '2021', class: 'Hypercar', specs: { engine: '6.0L V12', power: '850 hp', torque: '750 Nm', weight: '1050 kg', acceleration: '2.8s', topSpeed: '380 km/h', drivetrain: 'RWD' }, history: 'The sound of gods.', image: '', accentColor: '#a1a1aa' },
  { id: 'venom-f5', name: 'Venom F5', manufacturer: 'Hennessey', year: '2022', class: 'Hypercar', specs: { engine: '6.6L V8 TT', power: '1817 hp', torque: '1617 Nm', weight: '1360 kg', acceleration: '2.6s', topSpeed: '500 km/h', drivetrain: 'RWD' }, history: 'Built for speed.', image: '', accentColor: '#facc15' },
  { id: 'ssc-tuatara', name: 'Tuatara', manufacturer: 'SSC', year: '2020', class: 'Hypercar', specs: { engine: '5.9L V8 TT', power: '1750 hp', torque: '1735 Nm', weight: '1247 kg', acceleration: '2.5s', topSpeed: '475 km/h', drivetrain: 'RWD' }, history: 'Controversial speed king.', image: '', accentColor: '#000000' },

  // ====================== SUPER RARE (Legends / Group B) ======================
  { id: 'f40', name: 'F40', manufacturer: 'Ferrari', year: '1987', class: 'Supercar', specs: { engine: '2.9L V8 TT', power: '471 hp', torque: '577 Nm', weight: '1100 kg', acceleration: '4.1s', topSpeed: '324 km/h', drivetrain: 'RWD' }, history: 'Enzo\'s last car.', image: '', accentColor: '#ef4444' },
  { id: 'f50', name: 'F50', manufacturer: 'Ferrari', year: '1995', class: 'Supercar', specs: { engine: '4.7L V12', power: '512 hp', torque: '471 Nm', weight: '1230 kg', acceleration: '3.8s', topSpeed: '325 km/h', drivetrain: 'RWD' }, history: 'F1 engine for road.', image: '', accentColor: '#ef4444' },
  { id: 'enzo', name: 'Enzo', manufacturer: 'Ferrari', year: '2002', class: 'Supercar', specs: { engine: '6.0L V12', power: '651 hp', torque: '657 Nm', weight: '1255 kg', acceleration: '3.1s', topSpeed: '355 km/h', drivetrain: 'RWD' }, history: 'Named after the boss.', image: '', accentColor: '#dc2626' },
  { id: 'carrera-gt', name: 'Carrera GT', manufacturer: 'Porsche', year: '2004', class: 'Supercar', specs: { engine: '5.7L V10', power: '603 hp', torque: '590 Nm', weight: '1380 kg', acceleration: '3.5s', topSpeed: '330 km/h', drivetrain: 'RWD' }, history: 'Best V10 sound ever.', image: '', accentColor: '#d4d4d8' },
  { id: '959', name: '959 Komfort', manufacturer: 'Porsche', year: '1986', class: 'Supercar', specs: { engine: '2.8L Flat-6 TT', power: '444 hp', torque: '500 Nm', weight: '1450 kg', acceleration: '3.7s', topSpeed: '317 km/h', drivetrain: 'AWD' }, history: 'Most advanced car of the 80s.', image: '', accentColor: '#d4d4d8' },
  { id: 's1-quattro', name: 'Sport Quattro S1', manufacturer: 'Audi', year: '1985', class: 'Group B', specs: { engine: '2.1L I5 Turbo', power: '550 hp', torque: '590 Nm', weight: '1090 kg', acceleration: '3.1s', topSpeed: '220 km/h', drivetrain: 'AWD' }, history: 'Group B Monster.', image: '', accentColor: '#fbbf24' },
  { id: 'delta-s4', name: 'Delta S4', manufacturer: 'Lancia', year: '1985', class: 'Group B', specs: { engine: '1.8L Twincharged', power: '500+ hp', torque: '450 Nm', weight: '890 kg', acceleration: '2.4s', topSpeed: '225 km/h', drivetrain: 'AWD' }, history: 'Twincharged terror.', image: '', accentColor: '#b91c1c' },
  { id: '205-t16', name: '205 T16', manufacturer: 'Peugeot', year: '1984', class: 'Group B', specs: { engine: '1.8L Turbo', power: '450 hp', torque: '490 Nm', weight: '910 kg', acceleration: '2.9s', topSpeed: '210 km/h', drivetrain: 'AWD' }, history: 'Dominant rally force.', image: '', accentColor: '#fcd34d' },
  { id: 'rs200', name: 'RS200', manufacturer: 'Ford', year: '1984', class: 'Group B', specs: { engine: '1.8L Turbo', power: '450 hp', torque: '490 Nm', weight: '1050 kg', acceleration: '3.0s', topSpeed: '250 km/h', drivetrain: 'AWD' }, history: 'Ghia designed icon.', image: '', accentColor: '#2563eb' },
  { id: '037', name: '037', manufacturer: 'Lancia', year: '1982', class: 'Group B', specs: { engine: '2.0L SC', power: '325 hp', torque: '350 Nm', weight: '960 kg', acceleration: '4.0s', topSpeed: '220 km/h', drivetrain: 'RWD' }, history: 'Last RWD WRC winner.', image: '', accentColor: '#b91c1c' },
  { id: 'lfa', name: 'LFA', manufacturer: 'Lexus', year: '2010', class: 'Supercar', specs: { engine: '4.8L V10', power: '552 hp', torque: '480 Nm', weight: '1480 kg', acceleration: '3.7s', topSpeed: '325 km/h', drivetrain: 'RWD' }, history: 'Carbon masterpiece.', image: '', accentColor: '#fef08a' },
  { id: 'ford-gt-05', name: 'GT (2005)', manufacturer: 'Ford', year: '2005', class: 'Supercar', specs: { engine: '5.4L V8 SC', power: '550 hp', torque: '678 Nm', weight: '1538 kg', acceleration: '3.5s', topSpeed: '330 km/h', drivetrain: 'RWD' }, history: '100th Anniversary.', image: '', accentColor: '#1e3a8a' },
  { id: 'ford-gt-17', name: 'GT (2017)', manufacturer: 'Ford', year: '2017', class: 'Supercar', specs: { engine: '3.5L V6 TT', power: '647 hp', torque: '746 Nm', weight: '1385 kg', acceleration: '3.0s', topSpeed: '347 km/h', drivetrain: 'RWD' }, history: 'Le Mans winner.', image: '', accentColor: '#2563eb' },
  { id: 'aventador-svj', name: 'Aventador SVJ', manufacturer: 'Lamborghini', year: '2018', class: 'Supercar', specs: { engine: '6.5L V12', power: '759 hp', torque: '720 Nm', weight: '1525 kg', acceleration: '2.8s', topSpeed: '350 km/h', drivetrain: 'AWD' }, history: 'Nurburgring record holder.', image: '', accentColor: '#84cc16' },
  { id: 'murcielago-sv', name: 'Murcielago SV', manufacturer: 'Lamborghini', year: '2009', class: 'Supercar', specs: { engine: '6.5L V12', power: '661 hp', torque: '660 Nm', weight: '1565 kg', acceleration: '3.2s', topSpeed: '342 km/h', drivetrain: 'AWD' }, history: 'Old school brute.', image: '', accentColor: '#f97316' },
  { id: 'diablo-gtr', name: 'Diablo GTR', manufacturer: 'Lamborghini', year: '1999', class: 'Supercar', specs: { engine: '6.0L V12', power: '590 hp', torque: '640 Nm', weight: '1395 kg', acceleration: '3.5s', topSpeed: '338 km/h', drivetrain: 'RWD' }, history: 'Hardcore racer.', image: '', accentColor: '#facc15' },
  { id: 'countach', name: 'Countach QV', manufacturer: 'Lamborghini', year: '1985', class: 'Supercar', specs: { engine: '5.2L V12', power: '455 hp', torque: '500 Nm', weight: '1490 kg', acceleration: '4.8s', topSpeed: '298 km/h', drivetrain: 'RWD' }, history: 'Poster car.', image: '', accentColor: '#ffffff' },
  { id: 'miura', name: 'Miura SV', manufacturer: 'Lamborghini', year: '1971', class: 'Supercar', specs: { engine: '3.9L V12', power: '380 hp', torque: '400 Nm', weight: '1298 kg', acceleration: '6.5s', topSpeed: '290 km/h', drivetrain: 'RWD' }, history: 'The original.', image: '', accentColor: '#facc15' },
  { id: 'slr', name: 'SLR McLaren', manufacturer: 'Mercedes-Benz', year: '2003', class: 'Supercar', specs: { engine: '5.4L V8 SC', power: '617 hp', torque: '780 Nm', weight: '1750 kg', acceleration: '3.8s', topSpeed: '334 km/h', drivetrain: 'RWD' }, history: 'McMerc.', image: '', accentColor: '#d4d4d8' },
  { id: 'xj220', name: 'XJ220', manufacturer: 'Jaguar', year: '1992', class: 'Supercar', specs: { engine: '3.5L V6 TT', power: '542 hp', torque: '644 Nm', weight: '1470 kg', acceleration: '3.6s', topSpeed: '341 km/h', drivetrain: 'RWD' }, history: 'Fastest in the world (briefly).', image: '', accentColor: '#0f172a' },
  { id: 'gt2-rs', name: '911 GT2 RS', manufacturer: 'Porsche', year: '2018', class: 'Supercar', specs: { engine: '3.8L Flat-6 TT', power: '690 hp', torque: '750 Nm', weight: '1470 kg', acceleration: '2.8s', topSpeed: '340 km/h', drivetrain: 'RWD' }, history: 'The Widowmaker.', image: '', accentColor: '#d4d4d8' },
  { id: 'amg-black', name: 'AMG GT Black', manufacturer: 'Mercedes-AMG', year: '2021', class: 'Supercar', specs: { engine: '4.0L V8 TT', power: '720 hp', torque: '800 Nm', weight: '1588 kg', acceleration: '3.2s', topSpeed: '325 km/h', drivetrain: 'RWD' }, history: 'Flat plane crank.', image: '', accentColor: '#f97316' },
  { id: 'one-77', name: 'One-77', manufacturer: 'Aston Martin', year: '2009', class: 'Supercar', specs: { engine: '7.3L V12', power: '750 hp', torque: '750 Nm', weight: '1630 kg', acceleration: '3.7s', topSpeed: '354 km/h', drivetrain: 'RWD' }, history: 'Most powerful NA engine at launch.', image: '', accentColor: '#1e3a8a' },

  // ====================== RARE (JDM / WRC / Modern) ======================
  { id: 'r34', name: 'Skyline GT-R R34', manufacturer: 'Nissan', year: '2002', class: 'JDM', specs: { engine: 'RB26DETT', power: '276 hp', torque: '392 Nm', weight: '1560 kg', acceleration: '4.9s', topSpeed: '250 km/h', drivetrain: 'AWD' }, history: 'Godzilla.', image: '', accentColor: '#2563eb' },
  { id: 'r33', name: 'Skyline GT-R R33', manufacturer: 'Nissan', year: '1997', class: 'JDM', specs: { engine: 'RB26DETT', power: '276 hp', torque: '368 Nm', weight: '1530 kg', acceleration: '5.2s', topSpeed: '250 km/h', drivetrain: 'AWD' }, history: 'First production car under 8m at Ring.', image: '', accentColor: '#4b5563' },
  { id: 'r32', name: 'Skyline GT-R R32', manufacturer: 'Nissan', year: '1989', class: 'JDM', specs: { engine: 'RB26DETT', power: '276 hp', torque: '353 Nm', weight: '1430 kg', acceleration: '5.6s', topSpeed: '251 km/h', drivetrain: 'AWD' }, history: 'The original Godzilla.', image: '', accentColor: '#374151' },
  { id: 'supra', name: 'Supra RZ', manufacturer: 'Toyota', year: '1998', class: 'JDM', specs: { engine: '2JZ-GTE', power: '320 hp', torque: '427 Nm', weight: '1510 kg', acceleration: '4.6s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'The 10 second car.', image: '', accentColor: '#f97316' },
  { id: 'nsx-r', name: 'NSX-R', manufacturer: 'Honda', year: '2002', class: 'JDM', specs: { engine: '3.2L V6', power: '290 hp', torque: '304 Nm', weight: '1270 kg', acceleration: '4.7s', topSpeed: '280 km/h', drivetrain: 'RWD' }, history: 'Senna\'s legacy.', image: '', accentColor: '#f9fafb' },
  { id: 'nsx-92', name: 'NSX', manufacturer: 'Honda', year: '1992', class: 'JDM', specs: { engine: '3.0L V6', power: '270 hp', torque: '285 Nm', weight: '1370 kg', acceleration: '5.9s', topSpeed: '270 km/h', drivetrain: 'RWD' }, history: 'The everyday supercar.', image: '', accentColor: '#ef4444' },
  { id: 'rx7', name: 'RX-7 Spirit R', manufacturer: 'Mazda', year: '2002', class: 'JDM', specs: { engine: '13B-REW', power: '276 hp', torque: '314 Nm', weight: '1280 kg', acceleration: '5.0s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'Rotary perfection.', image: '', accentColor: '#1e3a8a' },
  { id: '22b', name: 'Impreza 22B', manufacturer: 'Subaru', year: '1998', class: 'JDM', specs: { engine: '2.2L Flat-4', power: '280 hp', torque: '363 Nm', weight: '1270 kg', acceleration: '4.7s', topSpeed: '248 km/h', drivetrain: 'AWD' }, history: 'Holy grail Subaru.', image: '', accentColor: '#2563eb' },
  { id: 'evo6', name: 'Lancer Evo 6 TME', manufacturer: 'Mitsubishi', year: '1999', class: 'JDM', specs: { engine: '4G63T', power: '276 hp', torque: '373 Nm', weight: '1360 kg', acceleration: '4.4s', topSpeed: '240 km/h', drivetrain: 'AWD' }, history: 'Tommi Makinen Ed.', image: '', accentColor: '#ef4444' },
  { id: 'evo9', name: 'Lancer Evo 9 MR', manufacturer: 'Mitsubishi', year: '2006', class: 'JDM', specs: { engine: '4G63T', power: '286 hp', torque: '392 Nm', weight: '1490 kg', acceleration: '4.8s', topSpeed: '242 km/h', drivetrain: 'AWD' }, history: 'Peak Evo.', image: '', accentColor: '#9ca3af' },
  { id: 's2000', name: 'S2000 CR', manufacturer: 'Honda', year: '2008', class: 'JDM', specs: { engine: 'F22C1', power: '237 hp', torque: '220 Nm', weight: '1250 kg', acceleration: '6.2s', topSpeed: '241 km/h', drivetrain: 'RWD' }, history: '9000 RPM.', image: '', accentColor: '#facc15' },
  { id: 'dc2', name: 'Integra Type R', manufacturer: 'Honda', year: '1995', class: 'JDM', specs: { engine: 'B18C', power: '197 hp', torque: '181 Nm', weight: '1120 kg', acceleration: '6.5s', topSpeed: '233 km/h', drivetrain: 'FWD' }, history: 'Best FWD handling.', image: '', accentColor: '#ffffff' },
  { id: 'silvia', name: 'Silvia S15', manufacturer: 'Nissan', year: '1999', class: 'JDM', specs: { engine: 'SR20DET', power: '247 hp', torque: '274 Nm', weight: '1240 kg', acceleration: '5.6s', topSpeed: '235 km/h', drivetrain: 'RWD' }, history: 'Drift icon.', image: '', accentColor: '#2563eb' },
  { id: '300zx', name: '300ZX TT', manufacturer: 'Nissan', year: '1996', class: 'JDM', specs: { engine: '3.0L V6 TT', power: '300 hp', torque: '384 Nm', weight: '1600 kg', acceleration: '5.5s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'Tech marvel.', image: '', accentColor: '#dc2626' },
  { id: 'gto-tt', name: 'GTO Twin Turbo', manufacturer: 'Mitsubishi', year: '1997', class: 'JDM', specs: { engine: '3.0L V6 TT', power: '320 hp', torque: '427 Nm', weight: '1700 kg', acceleration: '5.0s', topSpeed: '260 km/h', drivetrain: 'AWD' }, history: 'Active aero pioneer.', image: '', accentColor: '#b91c1c' },
  { id: 'c4-wrc', name: 'C4 WRC', manufacturer: 'Citroën', year: '2007', class: 'WRC', specs: { engine: '2.0L Turbo', power: '315 hp', torque: '580 Nm', weight: '1230 kg', acceleration: '3.8s', topSpeed: '200 km/h', drivetrain: 'AWD' }, history: 'Loeb\'s weapon.', image: '', accentColor: '#dc2626' },
  { id: 'escort', name: 'Escort Cosworth', manufacturer: 'Ford', year: '1992', class: 'WRC', specs: { engine: '2.0L Turbo', power: '224 hp', torque: '304 Nm', weight: '1275 kg', acceleration: '5.7s', topSpeed: '232 km/h', drivetrain: 'AWD' }, history: 'Whale tail.', image: '', accentColor: '#2563eb' },
  { id: 'stratos', name: 'Stratos', manufacturer: 'Lancia', year: '1974', class: 'WRC', specs: { engine: '2.4L V6', power: '190 hp', torque: '226 Nm', weight: '980 kg', acceleration: '6.8s', topSpeed: '232 km/h', drivetrain: 'RWD' }, history: 'Built to rally.', image: '', accentColor: '#ef4444' },
  { id: 'celica', name: 'Celica GT-Four', manufacturer: 'Toyota', year: '1994', class: 'WRC', specs: { engine: '2.0L Turbo', power: '252 hp', torque: '304 Nm', weight: '1390 kg', acceleration: '5.9s', topSpeed: '240 km/h', drivetrain: 'AWD' }, history: 'Cheater car.', image: '', accentColor: '#ffffff' },
  { id: 'focus', name: 'Focus WRC', manufacturer: 'Ford', year: '1999', class: 'WRC', specs: { engine: '2.0L Turbo', power: '300 hp', torque: '550 Nm', weight: '1230 kg', acceleration: '4.2s', topSpeed: '200 km/h', drivetrain: 'AWD' }, history: 'McRae driven.', image: '', accentColor: '#2563eb' },
  { id: 'polo', name: 'Polo R WRC', manufacturer: 'Volkswagen', year: '2013', class: 'WRC', specs: { engine: '1.6L Turbo', power: '318 hp', torque: '430 Nm', weight: '1200 kg', acceleration: '3.9s', topSpeed: '200 km/h', drivetrain: 'AWD' }, history: 'Dominant era.', image: '', accentColor: '#1e3a8a' },
  { id: 'i20', name: 'i20 Coupe WRC', manufacturer: 'Hyundai', year: '2017', class: 'WRC', specs: { engine: '1.6L Turbo', power: '380 hp', torque: '450 Nm', weight: '1190 kg', acceleration: '3.8s', topSpeed: '200 km/h', drivetrain: 'AWD' }, history: 'Korean contender.', image: '', accentColor: '#3b82f6' },
  { id: 'yaris', name: 'GR Yaris WRC', manufacturer: 'Toyota', year: '2020', class: 'WRC', specs: { engine: '1.6L Turbo', power: '380 hp', torque: '425 Nm', weight: '1190 kg', acceleration: '3.7s', topSpeed: '200 km/h', drivetrain: 'AWD' }, history: 'Born from rally.', image: '', accentColor: '#ef4444' },
  { id: 'quattro', name: 'Ur-Quattro', manufacturer: 'Audi', year: '1980', class: 'WRC', specs: { engine: '2.1L Turbo', power: '197 hp', torque: '285 Nm', weight: '1290 kg', acceleration: '7.1s', topSpeed: '220 km/h', drivetrain: 'AWD' }, history: 'AWD Pioneer.', image: '', accentColor: '#fbbf24' },
  { id: '5turbo', name: 'R5 Turbo', manufacturer: 'Renault', year: '1980', class: 'WRC', specs: { engine: '1.4L Turbo', power: '158 hp', torque: '221 Nm', weight: '970 kg', acceleration: '6.9s', topSpeed: '200 km/h', drivetrain: 'RWD' }, history: 'Mid-engine hatch.', image: '', accentColor: '#ef4444' },
  { id: 'viper-acr', name: 'Viper ACR', manufacturer: 'Dodge', year: '2016', class: 'Track Special', specs: { engine: '8.4L V10', power: '645 hp', torque: '813 Nm', weight: '1500 kg', acceleration: '3.3s', topSpeed: '285 km/h', drivetrain: 'RWD' }, history: 'Record breaker.', image: '', accentColor: '#ffffff' },
  { id: 'gt3-rs', name: '911 GT3 RS', manufacturer: 'Porsche', year: '2022', class: 'Track Special', specs: { engine: '4.0L Flat-6', power: '518 hp', torque: '465 Nm', weight: '1450 kg', acceleration: '3.2s', topSpeed: '296 km/h', drivetrain: 'RWD' }, history: 'DRS enabled.', image: '', accentColor: '#ef4444' },
  { id: 'sto', name: 'Huracan STO', manufacturer: 'Lamborghini', year: '2021', class: 'Track Special', specs: { engine: '5.2L V10', power: '630 hp', torque: '565 Nm', weight: '1339 kg', acceleration: '3.0s', topSpeed: '310 km/h', drivetrain: 'RWD' }, history: 'Race car for road.', image: '', accentColor: '#3b82f6' },
  { id: 'pista', name: '488 Pista', manufacturer: 'Ferrari', year: '2018', class: 'Track Special', specs: { engine: '3.9L V8 TT', power: '710 hp', torque: '770 Nm', weight: '1385 kg', acceleration: '2.85s', topSpeed: '340 km/h', drivetrain: 'RWD' }, history: 'Track focused.', image: '', accentColor: '#ef4444' },
  { id: 'lt765', name: '765LT', manufacturer: 'McLaren', year: '2020', class: 'Track Special', specs: { engine: '4.0L V8 TT', power: '755 hp', torque: '800 Nm', weight: '1339 kg', acceleration: '2.7s', topSpeed: '330 km/h', drivetrain: 'RWD' }, history: 'Long tail.', image: '', accentColor: '#f97316' },

  // ====================== UNCOMMON (Touring / Muscle / Hot Hatches) ======================
  { id: 'e30', name: 'M3 E30', manufacturer: 'BMW', year: '1986', class: 'Touring', specs: { engine: '2.3L I4', power: '200 hp', torque: '240 Nm', weight: '1200 kg', acceleration: '6.7s', topSpeed: '235 km/h', drivetrain: 'RWD' }, history: 'God\'s Chariot.', image: '', accentColor: '#dc2626' },
  { id: 'e46', name: 'M3 E46 CSL', manufacturer: 'BMW', year: '2003', class: 'Touring', specs: { engine: '3.2L I6', power: '360 hp', torque: '370 Nm', weight: '1385 kg', acceleration: '4.9s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'Carbon airbox noise.', image: '', accentColor: '#9ca3af' },
  { id: '190e', name: '190E Evo II', manufacturer: 'Mercedes-Benz', year: '1990', class: 'Touring', specs: { engine: '2.5L I4', power: '232 hp', torque: '245 Nm', weight: '1340 kg', acceleration: '7.1s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'DTM Legend.', image: '', accentColor: '#000000' },
  { id: 'calibra', name: 'Calibra DTM', manufacturer: 'Opel', year: '1994', class: 'Touring', specs: { engine: '2.5L V6', power: '420 hp', torque: 'N/A', weight: '1040 kg', acceleration: '2.5s', topSpeed: '300 km/h', drivetrain: 'AWD' }, history: 'Aero master.', image: '', accentColor: '#ffffff' },
  { id: '155', name: '155 V6 Ti', manufacturer: 'Alfa Romeo', year: '1993', class: 'Touring', specs: { engine: '2.5L V6', power: '420 hp', torque: '290 Nm', weight: '1040 kg', acceleration: '2.5s', topSpeed: '300 km/h', drivetrain: 'AWD' }, history: '11k RPM scream.', image: '', accentColor: '#dc2626' },
  { id: 'volvo850', name: '850 Estate', manufacturer: 'Volvo', year: '1994', class: 'Touring', specs: { engine: '2.0L I5', power: '290 hp', torque: 'N/A', weight: '975 kg', acceleration: 'N/A', topSpeed: '250 km/h', drivetrain: 'FWD' }, history: 'Racing wagon.', image: '', accentColor: '#1e3a8a' },
  { id: 'rs2', name: 'RS2 Avant', manufacturer: 'Audi', year: '1994', class: 'Touring', specs: { engine: '2.2L I5 Turbo', power: '311 hp', torque: '410 Nm', weight: '1595 kg', acceleration: '4.8s', topSpeed: '262 km/h', drivetrain: 'AWD' }, history: 'Porsche built wagon.', image: '', accentColor: '#2563eb' },
  { id: 'lotus-carlton', name: 'Lotus Carlton', manufacturer: 'Lotus', year: '1990', class: 'Touring', specs: { engine: '3.6L I6 TT', power: '377 hp', torque: '568 Nm', weight: '1650 kg', acceleration: '5.2s', topSpeed: '285 km/h', drivetrain: 'RWD' }, history: 'Too fast for police.', image: '', accentColor: '#047857' },
  { id: 'm5-e39', name: 'M5 E39', manufacturer: 'BMW', year: '1998', class: 'Touring', specs: { engine: '4.9L V8', power: '394 hp', torque: '500 Nm', weight: '1795 kg', acceleration: '4.8s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'Best sedan ever.', image: '', accentColor: '#1e3a8a' },
  { id: 'c63', name: 'C63 AMG', manufacturer: 'Mercedes-Benz', year: '2008', class: 'Touring', specs: { engine: '6.2L V8', power: '451 hp', torque: '600 Nm', weight: '1730 kg', acceleration: '4.4s', topSpeed: '250 km/h', drivetrain: 'RWD' }, history: 'Tyre shredder.', image: '', accentColor: '#d4d4d8' },
  { id: 'mustang65', name: 'Mustang GT350', manufacturer: 'Shelby', year: '1965', class: 'Muscle', specs: { engine: '4.7L V8', power: '306 hp', torque: '446 Nm', weight: '1270 kg', acceleration: '6.5s', topSpeed: '210 km/h', drivetrain: 'RWD' }, history: 'The original pony.', image: '', accentColor: '#ffffff' },
  { id: 'camaro69', name: 'Camaro Z28', manufacturer: 'Chevrolet', year: '1969', class: 'Muscle', specs: { engine: '4.9L V8', power: '290 hp', torque: '393 Nm', weight: '1420 kg', acceleration: '7.4s', topSpeed: '200 km/h', drivetrain: 'RWD' }, history: 'Trans-Am racer.', image: '', accentColor: '#f97316' },
  { id: 'charger69', name: 'Charger R/T', manufacturer: 'Dodge', year: '1969', class: 'Muscle', specs: { engine: '7.0L V8', power: '425 hp', torque: '664 Nm', weight: '1760 kg', acceleration: '5.2s', topSpeed: '210 km/h', drivetrain: 'RWD' }, history: 'The General.', image: '', accentColor: '#f97316' },
  { id: 'gto', name: 'GTO Judge', manufacturer: 'Pontiac', year: '1969', class: 'Muscle', specs: { engine: '6.6L V8', power: '366 hp', torque: '603 Nm', weight: '1600 kg', acceleration: '6.2s', topSpeed: '200 km/h', drivetrain: 'RWD' }, history: 'The Judge.', image: '', accentColor: '#f97316' },
  { id: 'cuda', name: 'Hemi Cuda', manufacturer: 'Plymouth', year: '1971', class: 'Muscle', specs: { engine: '7.0L V8', power: '425 hp', torque: '664 Nm', weight: '1550 kg', acceleration: '5.6s', topSpeed: '215 km/h', drivetrain: 'RWD' }, history: 'Rare muscle.', image: '', accentColor: '#84cc16' },
  { id: 'gnx', name: 'GNX', manufacturer: 'Buick', year: '1987', class: 'Muscle', specs: { engine: '3.8L V6 Turbo', power: '276 hp', torque: '488 Nm', weight: '1600 kg', acceleration: '4.6s', topSpeed: '200 km/h', drivetrain: 'RWD' }, history: 'Vader\'s car.', image: '', accentColor: '#000000' },
  { id: 'foxbody', name: 'Mustang Cobra', manufacturer: 'Ford', year: '1993', class: 'Muscle', specs: { engine: '5.0L V8', power: '235 hp', torque: '380 Nm', weight: '1400 kg', acceleration: '5.9s', topSpeed: '225 km/h', drivetrain: 'RWD' }, history: 'Vanilla Ice.', image: '', accentColor: '#dc2626' },
  { id: 'zr1', name: 'Corvette ZR-1', manufacturer: 'Chevrolet', year: '1990', class: 'Muscle', specs: { engine: '5.7L V8', power: '375 hp', torque: '502 Nm', weight: '1570 kg', acceleration: '4.4s', topSpeed: '290 km/h', drivetrain: 'RWD' }, history: 'King of the Hill.', image: '', accentColor: '#dc2626' },
  { id: 'viper', name: 'Viper GTS', manufacturer: 'Dodge', year: '1996', class: 'Muscle', specs: { engine: '8.0L V10', power: '450 hp', torque: '664 Nm', weight: '1500 kg', acceleration: '4.0s', topSpeed: '298 km/h', drivetrain: 'RWD' }, history: 'No ABS. No mercy.', image: '', accentColor: '#2563eb' },
  { id: 'hellcat', name: 'Challenger Hellcat', manufacturer: 'Dodge', year: '2015', class: 'Muscle', specs: { engine: '6.2L V8 SC', power: '707 hp', torque: '881 Nm', weight: '2000 kg', acceleration: '3.6s', topSpeed: '320 km/h', drivetrain: 'RWD' }, history: 'Tire smoke machine.', image: '', accentColor: '#b91c1c' },
  { id: 'clio', name: 'Clio V6', manufacturer: 'Renault', year: '2003', class: 'Hatch', specs: { engine: '3.0L V6', power: '252 hp', torque: '300 Nm', weight: '1400 kg', acceleration: '5.8s', topSpeed: '245 km/h', drivetrain: 'RWD' }, history: 'Mid-engine hatch.', image: '', accentColor: '#2563eb' },
  { id: 'golf-mk1', name: 'Golf GTI mk1', manufacturer: 'Volkswagen', year: '1976', class: 'Hatch', specs: { engine: '1.6L I4', power: '110 hp', torque: '140 Nm', weight: '810 kg', acceleration: '9.0s', topSpeed: '182 km/h', drivetrain: 'FWD' }, history: 'The original hot hatch.', image: '', accentColor: '#ef4444' },
  { id: 'civic', name: 'Civic Type R EK9', manufacturer: 'Honda', year: '1997', class: 'Hatch', specs: { engine: '1.6L I4', power: '182 hp', torque: '160 Nm', weight: '1050 kg', acceleration: '6.7s', topSpeed: '225 km/h', drivetrain: 'FWD' }, history: 'VTEC kicked in.', image: '', accentColor: '#ffffff' },
  { id: 'ae86', name: 'Sprinter Trueno', manufacturer: 'Toyota', year: '1983', class: 'Hatch', specs: { engine: '1.6L I4', power: '128 hp', torque: '149 Nm', weight: '940 kg', acceleration: '8.5s', topSpeed: '195 km/h', drivetrain: 'RWD' }, history: 'Tofu delivery.', image: '', accentColor: '#ffffff' },
  { id: 'mini', name: 'Cooper S', manufacturer: 'Mini', year: '1963', class: 'Hatch', specs: { engine: '1.0L I4', power: '70 hp', torque: '84 Nm', weight: '640 kg', acceleration: '11.0s', topSpeed: '140 km/h', drivetrain: 'FWD' }, history: 'Giant killer.', image: '', accentColor: '#dc2626' },
  { id: 'abarth', name: '500 Abarth', manufacturer: 'Fiat', year: '1964', class: 'Hatch', specs: { engine: '0.7L I2', power: '32 hp', torque: 'N/A', weight: '500 kg', acceleration: 'N/A', topSpeed: '130 km/h', drivetrain: 'RWD' }, history: 'Small but angry.', image: '', accentColor: '#ffffff' },
  { id: 'megane', name: 'Megane R26.R', manufacturer: 'Renault', year: '2008', class: 'Hatch', specs: { engine: '2.0L Turbo', power: '227 hp', torque: '310 Nm', weight: '1230 kg', acceleration: '6.0s', topSpeed: '237 km/h', drivetrain: 'FWD' }, history: 'Ring record holder.', image: '', accentColor: '#facc15' },
  { id: 'focus-rs', name: 'Focus RS mk2', manufacturer: 'Ford', year: '2009', class: 'Hatch', specs: { engine: '2.5L I5 Turbo', power: '300 hp', torque: '440 Nm', weight: '1467 kg', acceleration: '5.9s', topSpeed: '263 km/h', drivetrain: 'FWD' }, history: '5 cylinder growl.', image: '', accentColor: '#84cc16' },
  { id: 'integrale', name: 'Delta Integrale', manufacturer: 'Lancia', year: '1993', class: 'Hatch', specs: { engine: '2.0L Turbo', power: '212 hp', torque: '314 Nm', weight: '1300 kg', acceleration: '5.7s', topSpeed: '220 km/h', drivetrain: 'AWD' }, history: 'Rally for the road.', image: '', accentColor: '#b91c1c' },
  { id: 'cosworth', name: 'Sierra Cosworth', manufacturer: 'Ford', year: '1986', class: 'Hatch', specs: { engine: '2.0L Turbo', power: '201 hp', torque: '276 Nm', weight: '1215 kg', acceleration: '6.5s', topSpeed: '240 km/h', drivetrain: 'RWD' }, history: 'The working class hero.', image: '', accentColor: '#2563eb' },
  { id: 'swift', name: 'Swift Sport', manufacturer: 'Suzuki', year: '2012', class: 'Hatch', specs: { engine: '1.6L I4', power: '134 hp', torque: '160 Nm', weight: '1045 kg', acceleration: '8.7s', topSpeed: '195 km/h', drivetrain: 'FWD' }, history: 'Budget fun.', image: '', accentColor: '#facc15' },
  { id: '2000gt', name: '2000GT', manufacturer: 'Toyota', year: '1967', class: 'Classic', specs: { engine: '2.0L I6', power: '148 hp', torque: '175 Nm', weight: '1120 kg', acceleration: '8.6s', topSpeed: '217 km/h', drivetrain: 'RWD' }, history: 'Japan\'s first supercar.', image: '', accentColor: '#ffffff' },
  { id: 'db5', name: 'DB5', manufacturer: 'Aston Martin', year: '1963', class: 'Classic', specs: { engine: '4.0L I6', power: '282 hp', torque: '390 Nm', weight: '1502 kg', acceleration: '8.0s', topSpeed: '230 km/h', drivetrain: 'RWD' }, history: 'Bond\'s ride.', image: '', accentColor: '#d4d4d8' },
  { id: 'e-type', name: 'E-Type', manufacturer: 'Jaguar', year: '1961', class: 'Classic', specs: { engine: '3.8L I6', power: '265 hp', torque: '352 Nm', weight: '1315 kg', acceleration: '7.0s', topSpeed: '241 km/h', drivetrain: 'RWD' }, history: 'Most beautiful car ever.', image: '', accentColor: '#047857' },
  { id: '300sl', name: '300SL Gullwing', manufacturer: 'Mercedes-Benz', year: '1954', class: 'Classic', specs: { engine: '3.0L I6', power: '215 hp', torque: '275 Nm', weight: '1300 kg', acceleration: '8.8s', topSpeed: '260 km/h', drivetrain: 'RWD' }, history: 'Gullwing doors.', image: '', accentColor: '#d4d4d8' },
  { id: 'testarossa', name: 'Testarossa', manufacturer: 'Ferrari', year: '1984', class: 'Classic', specs: { engine: '4.9L Flat-12', power: '390 hp', torque: '490 Nm', weight: '1506 kg', acceleration: '5.3s', topSpeed: '290 km/h', drivetrain: 'RWD' }, history: 'Miami Vice.', image: '', accentColor: '#ef4444' },
  { id: 'countach-lp400', name: 'Countach LP400', manufacturer: 'Lamborghini', year: '1974', class: 'Classic', specs: { engine: '3.9L V12', power: '370 hp', torque: '361 Nm', weight: '1065 kg', acceleration: '5.4s', topSpeed: '290 km/h', drivetrain: 'RWD' }, history: 'The Periscopio.', image: '', accentColor: '#facc15' },
  { id: 'cobra', name: 'Shelby Cobra 427', manufacturer: 'Shelby', year: '1965', class: 'Classic', specs: { engine: '7.0L V8', power: '425 hp', torque: '650 Nm', weight: '1068 kg', acceleration: '4.2s', topSpeed: '262 km/h', drivetrain: 'RWD' }, history: 'V8 in a bathtub.', image: '', accentColor: '#2563eb' }
];