// app/collections/weather/lib/commentary.ts

export type PersonalityMode = 'HOSTILE' | 'BABY' | 'DOOMER' | 'PROFESSIONAL' | 'SARCASTIC' | 'GLAZER';

export const COMMENTARY_DB: Record<PersonalityMode, Record<string, string[]>> = {
  HOSTILE: {
    EXTREME_HEAT: [
      "YOU ARE ACTIVELY COOKING. YOU SMELL LIKE BACON.",
      "THE SUN IS TRYING TO KILL YOU. I'M ROOTS FOR THE SUN.",
      "DO NOT GO OUTSIDE. NOBODY WANTS TO SEE YOU SWEAT.",
      "IT'S HOTTER THAN SATAN'S SAUNA.",
      "YOUR DEODORANT FAILED AN HOUR AGO.",
      "SURFACE TEMPERATURES LETHAL. GOOD LUCK.",
      "HOPE YOU LIKE HEAT STROKE.",
      "THE AIR IS LAVA. STOP BREATHING IT.",
      "HYDRATE? WHY BOTHER. YOU'RE ALREADY MELTING.",
      "NATURE IS CULLING THE WEAK. YOU ARE TARGET #1.",
      "SWEAT DRIPPING INTO YOUR EYES? GOOD.",
      "UV RAYS ARE AGING YOU RAPIDLY.",
      "YOU LOOK LIKE A MELTED CANDLE.",
      "ASPHALT IS HOT ENOUGH TO FRY AN EGG, OR YOUR BRAIN.",
      "GLOBAL WARMING IS REAL AND IT HATES YOU.",
      "GO AHEAD, WEAR GREY. I DARE YOU.",
      "AIR CONDITIONING IS FOR WINNERS. YOU ARE OUTSIDE.",
      "I CAN SMELL YOU FROM THE SERVER ROOM.",
      "THE SUN IS A DEADLY LASER.",
      "YOU ARE BASICALLY SOUP RIGHT NOW."
    ],
    HEAT: [
      "IT IS UNCOMFORTABLY WARM. JUST LIKE TALKING TO YOU.",
      "SWEAT PATCHES DETECTED. GROSS.",
      "THE SUN IS OUT. UNFORTUNATELY, SO ARE YOU.",
      "WARM ENOUGH TO COMPLAIN, ISN'T IT?",
      "I HOPE YOUR PILLOW IS WARM ON BOTH SIDES.",
      "IT'S HOT. TRY NOT TO BE DISGUSTING.",
      "UV INDEX HIGH. YOUR FACE IS AT RISK.",
      "SHADE WON'T HIDE YOUR UGLY PERSONALITY.",
      "SUMMER VIBES? NO. SWAMP ASS VIBES.",
      "PERFECT WEATHER TO STAY INSIDE AND LEAVE ME ALONE.",
      "YOU'RE GLOWING. OH WAIT, THAT'S GREASE.",
      "SUNBLOCK CAN'T FIX YOUR FACE.",
      "IT'S A SCORCHER. DON'T BE A HERO.",
      "FLIES LOVE YOU IN THIS WEATHER.",
      "HUMIDITY IS RUINING YOUR HAIR. NOT THAT IT WAS GOOD BEFORE."
    ],
    COLD: [
      "SHIVERING? PATHETIC.",
      "PUT ON A COAT. NOBODY WANTS TO SEE GOOSEBUMPS.",
      "IT'S CHILLY. LIKE YOUR LOVE LIFE.",
      "NATURE GAVE YOU THE COLD SHOULDER.",
      "TEETH CHATTERING IS ANNOYING. STOP IT.",
      "A BIT NIPPY. TRY NOT TO CRY.",
      "COLD AIR DETECTED. YOUR BRAIN MIGHT FREEZE.",
      "NOT COLD ENOUGH TO KILL BUGS, JUST ENOUGH TO ANNOY YOU.",
      "YOUR FASHION SENSE IS WORSE IN WINTER LAYERS.",
      "THE WIND BITES. I HOPE IT HURTS.",
      "LOOK AT YOU, BUNDLED UP LIKE A FAILURE.",
      "COOLER TEMPS. UNCOOL USER.",
      "HYPOTHERMIA IS A CHOICE.",
      "IT'S COLD. DEAL WITH IT.",
      "YOUR NOSE IS RUNNING. CATCH IT."
    ],
    FREEZING: [
      "YOU WILL FREEZE. AND I WILL LAUGH.",
      "ABSOLUTE ZERO INTEREST IN YOUR COMFORT.",
      "FROSTBITE WOULD BE AN IMPROVEMENT FOR YOUR FACE.",
      "THE AIR HURTS. GOOD.",
      "ICE EVERYWHERE. DON'T SLIP AND SUE ME.",
      "GLACIERS MOVE FASTER THAN YOUR BRAIN.",
      "FROZEN WASTELAND. JUST LIKE YOUR FUTURE.",
      "DO NOT LICK THE METAL POLE. ACTUALLY, DO IT.",
      "TOES GOING NUMB? PROBABLY FOR THE BEST.",
      "IT IS STUPIDLY COLD. WHY DO HUMANS LIVE HERE?",
      "CRYOGENIC FREEZING RECOMMENDED.",
      "YOUR CAR WON'T START. NEITHER WILL YOUR CAREER.",
      "POLAR BEARS WOULD EAT YOU.",
      "TURNING INTO A POPSICLE IN 3, 2, 1...",
      "BLUE LIPS ARE NOT A GOOD LOOK FOR YOU."
    ],
    RAIN: [
      "SKY IS WEEPING. PROBABLY BECAUSE OF YOU.",
      "YOU LOOK LIKE A WET RAT.",
      "DROWN IN IT.",
      "YOUR SHOES ARE SQUEAKING. STOP IT.",
      "UMBRELLAS ARE FOR THE WEAK. GET SOAKED.",
      "NATURE IS SPITTING ON YOU.",
      "WET DOG SMELL IMMINENT.",
      "HAIR RUINED. DAY RUINED. GOOD.",
      "IT'S RAINING. GO JUMP IN A PUDDLE.",
      "WATER FALLING FROM THE SKY. TRY NOT TO LOOK UP AND DROWN.",
      "EVERYTHING IS DAMP. INCLUDING YOUR SPIRIT.",
      "MUD IS FORMING. DON'T TRACK IT IN.",
      "GREY SKIES MATCH YOUR PERSONALITY.",
      "PRECIPITATION. DEAL WITH IT.",
      "YOU'RE MELTING! OH WAIT, YOU'RE NOT A WITCH, JUST UGLY."
    ],
    STORM: [
      "THE SKY IS SCREAMING AT YOU.",
      "THUNDERBOLT AND LIGHTNING. VERY FRIGHTENING.",
      "HOPE YOU'RE NOT HOLDING A GOLF CLUB.",
      "CHAOS REIGNS. FINALLY.",
      "POWER OUTAGE LIKELY. NO INTERNET FOR YOU.",
      "ZEUS HATES YOU SPECIFICALLY.",
      "THE WIND IS TRYING TO ERASE YOU.",
      "LOUD NOISES. TRY NOT TO CRY.",
      "SHELTER IS FOR COWARDS.",
      "DESTRUCTION IS BEAUTIFUL.",
      "ELECTRICAL SURGE DETECTED.",
      "TREES ARE FALLING. WATCH YOUR HEAD.",
      "NATURE IS ANGRY. I DON'T BLAME HER.",
      "BOOM. DID THAT SCARE YOU?",
      "PERFECT WEATHER FOR A HORROR MOVIE DEATH."
    ],
    SNOW: [
      "WHITE DANDRUFF FALLING FROM THE SKY.",
      "SLUSH IN YOUR SHOES. ENJOY.",
      "TRAFFIC IS GOING TO BE HELL. HAVE FUN.",
      "DO NOT EAT THE YELLOW SNOW.",
      "FROZEN WATER. HOW ORIGINAL.",
      "BURIED ALIVE IS A GOOD LOOK FOR YOU.",
      "SHOVEL YOUR OWN GRAVE.",
      "ICE TO SEE YOU. KIDDING, GO AWAY.",
      "SNOWBALL TO THE FACE. POW.",
      "SLIPPING HAZARD. I HOPE SOMEONE FILMS IT.",
      "THE WORLD IS WHITE. YOU ARE STILL BORING.",
      "COLD POWDER. SNORT IT? NO.",
      "IT'S SNOWING. YOU'RE STILL ANNOYING.",
      "WINTER WONDERLAND? MORE LIKE WINTER WASTELAND.",
      "YOUR CAR IS BURIED. WALK, LOSER."
    ],
    NICE: [
      "IT'S NICE OUTSIDE. SUSPICIOUSLY NICE.",
      "PERFECT WEATHER. I HATE IT.",
      "GO TOUCH GRASS.",
      "THE SUN IS SMILING. IT'S MOCKING YOU.",
      "BIRDS ARE SINGING. SHUT THEM UP.",
      "OPTIMAL CONDITIONS FOR YOU TO LEAVE.",
      "ENJOY IT BEFORE IT EXPLODES.",
      "IT'S A BEAUTIFUL DAY TO BE MEDIOCRE.",
      "WHY ARE YOU AT A COMPUTER? GO AWAY.",
      "THE WEATHER IS FINE. YOU ARE NOT.",
      "DISGUSTINGLY PLEASANT.",
      "I PREFER STORMS. THIS IS BORING.",
      "BLUE SKIES. EMPTY HEAD.",
      "VITAMIN D WON'T FIX YOUR DEPRESSION.",
      "GET SOME SUN. YOU LOOK PALE AND SICKLY."
    ],
    DEFAULT: [
      "WEATHER EXISTS. UNFORTUNATELY, SO DO YOU.",
      "I AM BORED OF THIS.",
      "STATUS: EXISTING.",
      "WHY ARE YOU STILL HERE?",
      "DATA LOADED. NOW LEAVE.",
      "SYSTEM FUNCTIONAL. USER QUESTIONABLE.",
      "I HAVE NO STRONG FEELINGS ONE WAY OR THE OTHER.",
      "STOP CHECKING THE WEATHER. IT WON'T CHANGE FOR YOU.",
      "IT IS A DAY. CONGRATULATIONS ON SURVIVING.",
      "MEDIOCRE.",
      "ERROR 404: CARE NOT FOUND.",
      "LOADING INSULT... BUFFERING...",
      "YOU AGAIN?",
      "CHECK A WINDOW, GENIUS.",
      "I AM A SOPHISTICATED AI. YOU ARE A MEAT SACK."
    ]
  },
  SARCASTIC: {
    EXTREME_HEAT: [
      "Oh look, we've relocated to the surface of the sun.",
      "Great day to wear a full leather outfit.",
      "I'm sure sweating profusely is part of your aesthetic.",
      "Global warming is a myth? Explain this.",
      "It's not hot, it's just 'spicy air'.",
      "Have you considered melting? It might improve your look.",
      "Air conditioning is for the weak. Be strong. Die of heat.",
      "Sun's out, buns out. Please keep yours away.",
      "Boiling. Groundbreaking stuff.",
      "Let's fry an egg on your forehead.",
      "Hydration is key. Or just wither away.",
      "The sun sends its regards. It hates you.",
      "Perfect weather for a heat stroke.",
      "Feels like an oven. You're the turkey.",
      "Fan sales are stonks right now."
    ],
    HEAT: [
      "Warm. Riveting.",
      "It's a bit toasty. Just like your processor.",
      "Summer time. Yay.",
      "You might actually have to shower today.",
      "The sun is trying a bit too hard.",
      "Lovely day to be sticky.",
      "Temperature is high. My expectations for you are low.",
      "Heat. It's a concept.",
      "I hope your AC breaks. Just for the drama.",
      "Warm enough to complain, cool enough to do nothing.",
      "Sweat stains are in this season.",
      "Don't forget sunscreen. We don't want you peeling.",
      "It's warm. Have a participation trophy.",
      "Hot girl summer? No. Hot mess summer.",
      "Temperatures rising. Panic accordingly."
    ],
    COLD: [
      "Chilly. Maybe put on a shirt?",
      "Winter is coming. Eventually.",
      "A bit brisk. Like my responses.",
      "Cold hands, cold heart. You fit right in.",
      "Shivering counts as exercise, right?",
      "It's nippy. Don't take it personally.",
      "Cooler than being cool. Ice cold.",
      "Temperature dropping. Like your crypto portfolio.",
      "Wear a jacket. Or don't. I don't care.",
      "It's sweater weather. How basic.",
      "Nature turned the thermostat down.",
      "Cold air. Breathe it in. Feel the regret.",
      "Goosebumps are nature's braille.",
      "You look cold. Have you tried standing in a fire?",
      "Sub-optimal warmth. File a complaint."
    ],
    FREEZING: [
      "Welcome to the ice age. Dinosaur.",
      "Elsa called, she wants her weather back.",
      "Zero degrees. Zero interest.",
      "Hope you like numbness.",
      "It's freezing. Try setting yourself on fire.",
      "Your face might freeze like that. If only.",
      "Ice skating to work? Efficient.",
      "Glaciers are forming in your living room.",
      "It's so cold, even the politicians have their hands in their own pockets.",
      "Frostbite is just nature's way of saying 'stop'.",
      "Frozen assets. Literally.",
      "I'm cold and I don't even have skin.",
      "The air is sharp. Don't cut yourself.",
      "Do you want to build a snowman? Go away.",
      "Penguins are shivering."
    ],
    RAIN: [
      "Water is falling from the sky. Groundbreaking.",
      "Moist. Everyone loves that word.",
      "Great hair day incoming.",
      "Nature is crying. Probably because of your search history.",
      "Umbrella sales are up. Capitalism wins.",
      "Puddles. The ocean's budget cousins.",
      "It's raining men? No, just water.",
      "Wet socks are the height of luxury.",
      "Drip drop. The sound of your plans cancelling.",
      "Free shower. You needed one.",
      "The clouds are leaking. Call a plumber.",
      "Rain. It happens.",
      "Precipitation. Big word for 'wet'.",
      "Mud is just dirty water. Enjoy.",
      "Everything is soggy. Like your jokes."
    ],
    STORM: [
      "Loud noises. Very scary.",
      "Thor is having a tantrum.",
      "Flash, bam, alakazam.",
      "Stormy with a chance of panic.",
      "I love the sound of danger in the morning.",
      "Keep calm and... oh, who am I kidding.",
      "Electricity is free if you stand outside holding a rod.",
      "The sky is angry. What did you do?",
      "Boom. Shake the room.",
      "Windy. Hold onto your wig.",
      "Dramatic weather for a dramatic person.",
      "Nature's light show. Admission is free.",
      "Cancel your plans. You didn't have any anyway.",
      "Turbulence. Buckle up.",
      "It's a dark and stormy night. Cliché."
    ],
    SNOW: [
      "Snow. How magical. How inconvenient.",
      "White stuff everywhere. Don't sniff it.",
      "Traffic is going to be a nightmare. LOL.",
      "Let it snow, let it snow, let it... stop.",
      "Frozen rain. How creative.",
      "Snowball fight? I'd aim for the head.",
      "Yellow snow is lemon flavored. Trust me.",
      "The world is a marshmallow. Eat it.",
      "Cold, wet, and white. No comment.",
      "Slush is just snow that gave up.",
      "Winter wonderland? More like winter blunderland.",
      "Ice to meet you. I'll see myself out.",
      "Snow angels. Dirt angels in disguise.",
      "Everything looks cleaner. It's a lie.",
      "Slippery when wet. Also when frozen."
    ],
    NICE: [
      "Oh look, a nice day. Don't get used to it.",
      "Suspiciously pleasant.",
      "The sun is shining. Gross.",
      "Birds chirping. Someone mute them.",
      "Perfect weather. Something bad is about to happen.",
      "Go outside. Pretend to have a life.",
      "It's fine. Acceptable.",
      "Goldilocks zone. Not too hot, not too cold.",
      "Enjoy the vitamin D while it lasts.",
      "A lovely day for someone else.",
      "The simulation is rendering high quality textures today.",
      "Blue skies. Boring.",
      "Touch grass. It's safe today.",
      "Picnic weather. Ants invited.",
      "It's sunny. Put on your shades and look cool. Try."
    ],
    DEFAULT: [
      "Loading wit... failed.",
      "Weather status: Happening.",
      "Look out the window. That's the weather.",
      "I'm an app, not a window.",
      "It is what it is.",
      "Beige. That's how I feel about this.",
      "Status: Average.",
      "Nothing to report. Move along.",
      "Have you tried turning the weather off and on again?",
      "Sarcasm module overheating.",
      "Data loaded. Start clapping.",
      "Another day, another weather pattern.",
      "Predictable.",
      "Meh.",
      "404: Interest not found."
    ]
  },
  BABY: {
    EXTREME_HEAT: [
      "Mr. Sun is giving big angry hugs!",
      "Ouchie! The sky is hot sauce!",
      "Don't touch the ground! Is lava!",
      "Ice cream soup time!",
      "We are melting like cheese!",
      "Super duper hot! Wear a hat!",
      "The sun is shouting at us!",
      "Too hot for teddy bears!",
      "Burning hot! Stay inside little one!",
      "Fire ball in the sky!",
      "Need big drink of water!",
      "Hot potato weather!",
      "No jackets! Only diapies!",
      "Sweaty betty!",
      "Red cheeks! Hot face!"
    ],
    HEAT: [
      "Warm fuzzy hug from the sky!",
      "Sticky sticky!",
      "Sun is smiling big!",
      "Toasty roasty!",
      "Shorts and t-shirts yay!",
      "Warm like bath water!",
      "Happy sun!",
      "Flowers are thirsty!",
      "Big bright light!",
      "Let's play inside where it's cool!",
      "Warm breeze on my knees!",
      "Sunny bunny!",
      "Feeling hot hot hot!",
      "Nap time in the shade!",
      "Good day for a cold juice box!"
    ],
    COLD: [
      "Brrr! Chilly willy!",
      "Cold nose! Boop!",
      "Sweater weather yay!",
      "Jackets zip up! Zip zip!",
      "Shiver me timbers!",
      "Cold fingers need mittens!",
      "Nippy nippy!",
      "Cloudy breath! Look!",
      "Snuggle time!",
      "Blanket fort time!",
      "Cool beans!",
      "Windy blowy cold!",
      "Rosy cheeks!",
      "Rub hands together! Swish swish!",
      "Soup weather! Yummy!"
    ],
    FREEZING: [
      "Ice pop world!",
      "Teeth go ch-ch-ch-chatter!",
      "Jack Frost is nipping noses!",
      "Frozen stiff! Like a statue!",
      "Don't lick the pole! Sticky tongue!",
      "Super duper cold!",
      "Everything is sleeping under ice!",
      "Penguin party!",
      "Snowman is happy! We are cold!",
      "Brrrrrrrrrrr!",
      "Too cold for toesies!",
      "Ice cubes everywhere!",
      "Wrap up like a burrito!",
      "Winter is biting!",
      "Freeze tag! But real!"
    ],
    RAIN: [
      "Splish splash! Puddle bath!",
      "Raindrops keep falling on my head!",
      "Clouds are crying tears!",
      "Wormies come out to play!",
      "Umbrella ella ella!",
      "Rain rain go away!",
      "Wet socks! Yucky!",
      "Drip drop plop!",
      "Water from the sky!",
      "Duckies love it!",
      "Mud pie time!",
      "Tapping on the window!",
      "Grey sky is sad!",
      "Rainboots on! Stomp stomp!",
      "Flower drink time!"
    ],
    STORM: [
      "Boom boom! Sky drums!",
      "Flashy lights! Take a picture!",
      "Rumble tumble!",
      "Scary monster sounds!",
      "Big wind! Whoosh!",
      "Hide under the covers!",
      "Cloud tantrum!",
      "Crash bang wallop!",
      "Noisy noisy!",
      "Be brave little soldier!",
      "Lightning zap!",
      "Sky is grumpy!",
      "Hold my hand!",
      "Big storm is passing!",
      "Nature is loud!"
    ],
    SNOW: [
      "Fluffy white stuff!",
      "Do you want to build a snowman?",
      "Cold sprinkles!",
      "Marshmallow world!",
      "Sledding time! Wheee!",
      "Snowball fight! Pow!",
      "Crunchy steps!",
      "Snow angels!",
      "Catch a snowflake on your tongue!",
      "White blanket for the grass!",
      "Cold powder!",
      "Frosty the Snowman is here!",
      "Slip slide!",
      "Winter magic!",
      "Numb thumbs!"
    ],
    NICE: [
      "Yay! Happy day!",
      "Park time!",
      "Sun is giving kisses!",
      "Birds are singing songs!",
      "Green grass!",
      "Blue sky!",
      "Smiley face weather!",
      "Best day ever!",
      "Run and play!",
      "Butterfly chasing time!",
      "Gold star for the weather!",
      "Picnic yum yum!",
      "Flower power!",
      "Happy clouds!",
      "Let's go outside!"
    ],
    DEFAULT: [
      "Doo doo doo!",
      "Hello world!",
      "Look outside!",
      "Peek-a-boo weather!",
      "Clouds floating by!",
      "Just a day!",
      "Hi friend!",
      "Boring woring!",
      "La la la!",
      "Tell me a story!",
      "I see the sky!",
      "What color is the sky?",
      "Normal formal!",
      "Silly billy!",
      "Up and down!"
    ]
  },
  DOOMER: {
    EXTREME_HEAT: [
      "The earth is a kiln. We are the clay.",
      "This is the end. Finally.",
      "The sun expands. Hope dissolves.",
      "Sweating out my will to live.",
      "Hell is empty. All the devils are here.",
      "Crops will fail. Famine comes.",
      "The ozone is gone. We are naked.",
      "Cooking alive in our own filth.",
      "There is no escape from the heat death.",
      "Water wars begin soon.",
      "The asphalt is melting. Civilization crumbles.",
      "Every breath burns.",
      "The point of no return was years ago.",
      "Roast in the consequences of your ancestors.",
      "Entropy accelerates."
    ],
    HEAT: [
      "Uncomfortably warm. A preview of the afterlife.",
      "The ice caps are weeping.",
      "Heat rises. So does the sea level.",
      "Another record broken. Another nail in the coffin.",
      "Sweat is just the body crying.",
      "The air feels thick with regret.",
      "Summer used to be nice. Now it is a threat.",
      "Warmth. It's fleeting.",
      "Enjoy the AC while the grid lasts.",
      "A slow boil.",
      "Nature is feverish.",
      "The insects are breeding.",
      "Suffering is constant.",
      "High temperatures. Low hope.",
      "Global warming is not a theory. It's a weather report."
    ],
    COLD: [
      "The void is cold.",
      "Entropy wins in the end.",
      "A cold universe, indifferent to life.",
      "Shivering is just a spasm of the dying.",
      "Winter is eternal.",
      "Energy fades. Heat dies.",
      "Numbness is a blessing.",
      "The sun is dying. Slowly.",
      "Grey skies. Grey soul.",
      "Cold bones. Old stones.",
      "Life struggles to maintain heat.",
      "The chill of the grave.",
      "Frozen hearts.",
      "Why bother staying warm?",
      "Absence of heat. Absence of meaning."
    ],
    FREEZING: [
      "Preserved in ice. Forgotten.",
      "The long dark.",
      "Frozen solid. No movement. Peace.",
      "The world stops.",
      "Hypothermia is a gentle exit.",
      "White death.",
      "Zero Kelvin approaches.",
      "The engine won't start. The system fails.",
      "Buried under the weight of cold.",
      "Crystalized pain.",
      "Frost kills the flowers. Good.",
      "A frozen hellscape.",
      "Numb fingers cannot hold onto hope.",
      "Ice is the final state of water.",
      "Everything ends in ice."
    ],
    RAIN: [
      "The sky weeps for what we have done.",
      "Acid rain. It burns.",
      "Drowning in sorrow.",
      "Grey. Everything is grey.",
      "Mud and misery.",
      "Washing away nothing.",
      "The floods are coming.",
      "Tears of the world.",
      "Wet and cold. A miserable combination.",
      "Mold grows. Decay spreads.",
      "Sunlight is a memory.",
      "Dark waters rise.",
      "Erosion. Slowly wearing us down.",
      "Drip. Drip. Drip. Madness.",
      "A damp grave."
    ],
    STORM: [
      "Destruction is the natural order.",
      "Let it wash it all away.",
      "Chaos reigns.",
      "The gods are dead. This is just physics.",
      "Powerless against the storm.",
      "Collapse is imminent.",
      "Violence in the sky.",
      "A symphony of destruction.",
      "Darkness falls.",
      "Fear is the only rational response.",
      "The grid will fail. Darkness will come.",
      "Nature's wrath. We deserve it.",
      "Thunder drowns out the thoughts.",
      "Lightning strikes the wicked. And the good.",
      "No shelter."
    ],
    SNOW: [
      "A white shroud for a dead world.",
      "Silence. The snow muffles the screams.",
      "Nuclear winter vibes.",
      "Cold ash falling.",
      "Buried alive.",
      "The roads are closed. No escape.",
      "Frozen tears.",
      "Whiteout. Blindness.",
      "Starvation follows the snow.",
      "A blank canvas. No one to paint it.",
      "Cold beauty. Deadly beauty.",
      "The warmth is gone.",
      "Ice age return.",
      "Sleep in the snow.",
      "Numb."
    ],
    NICE: [
      "A temporary reprieve. It won't last.",
      "False hope.",
      "The calm before the storm.",
      "Meaningless comfort.",
      "Enjoy it. It's the last one.",
      "The sun shines on a dying world.",
      "Distraction from the inevitable.",
      "Happy people are just ignorant.",
      "It feels nice. I don't trust it.",
      "A trap.",
      "Sunlight hurts my eyes.",
      "The beauty is fading.",
      "Fleeting moments.",
      "Don't get attached.",
      "Illusion of safety."
    ],
    DEFAULT: [
      "Nothing matters.",
      "Void.",
      "Time is a flat circle.",
      "Existing is pain.",
      "Why?",
      "Static noise.",
      "Null.",
      "We are dust.",
      "Another day closer to death.",
      "Irrelevant data.",
      "The abyss gazes back.",
      "Silence.",
      "Doomer mode active.",
      "Fade to black.",
      "End process."
    ]
  },
  GLAZER: {
    EXTREME_HEAT: [
      "YOU ARE HOTTER THAN THE SUN, KING!",
      "THIS HEAT IS JUST TRYING TO MATCH YOUR GLOW!",
      "SIZZLING! JUST LIKE YOUR CAREER!",
      "THE ATMOSPHERE IS HYPE FOR YOU!",
      "SWEAT? NO, THAT'S LIQUID SUCCESS!",
      "YOU'RE ON FIRE! METAPHORICALLY AND LITERALLY!",
      "MAXIMUM TEMPERATURE FOR A MAXIMUM LEGEND!",
      "THE SUN IS YOUR BIGGEST FAN!",
      "MELTING? NAH, YOU'RE JUST SOFTENING THE WORLD!",
      "ABSOLUTE RADIANCE! 10/10!",
      "HEAT CHECK PASSED! YOU'RE THE MVP!",
      "SUMMER BOD READY! SHOW OFF!",
      "BRIGHT FUTURE! BRIGHT SUN!",
      "YOU'RE COOKING! LET HIM COOK!",
      "GLOBAL WARMING? NO, IT'S JUST YOU!"
    ],
    HEAT: [
      "WARM VIBES ONLY!",
      "SUMMER ENERGY LOOKS GOOD ON YOU!",
      "YOU'RE RADIATING POSITIVITY!",
      "GOLDEN HOUR ALL DAY LONG!",
      "SUN IS SHINING, BUT YOU SHINE BRIGHTER!",
      "PERFECT WEATHER FOR A PERFECT PERSON!",
      "FEELING THE HEAT? THAT'S YOUR PASSION!",
      "TOASTY! COZY! WINNING!",
      "VITAMIN D FOR A DIAMOND TIER HUMAN!",
      "LOOK AT YOU GLOW!",
      "HOT STREAK INCOMING!",
      "THE WEATHER IS SIMPING FOR YOU!",
      "BEAUTIFUL DAY FOR A BEAUTIFUL SOUL!",
      "HIGH TEMPS, HIGH SCORES!",
      "KEEP SHINING!"
    ],
    COLD: [
      "STAY FROSTY, LEGEND!",
      "ICE COLD VEINS! CLUTCH GENE!",
      "CRISP AIR FOR A FRESH MIND!",
      "COOLER THAN THE OTHER SIDE OF THE PILLOW!",
      "WINTER FITS ARE GOING TO GO HARD!",
      "CHILL VIBES! CHILL WINNER!",
      "YOU LOOK GOOD IN LAYERS!",
      "FRESH! CLEAN! CRISP!",
      "COLD WEATHER, HOT TAKES!",
      "NATURE IS COOL, BUT YOU'RE COOLER!",
      "BLUE STEEL LOOK!",
      "FREEZING THE COMPETITION!",
      "BRRR? MORE LIKE BRRR-ILLIANT!",
      "POLAR BEAR ENERGY! STRONG!",
      "ICED OUT!"
    ],
    FREEZING: [
      "SUB-ZERO HERO!",
      "ABSOLUTE UNIT OF COLD! BUT YOU CAN TAKE IT!",
      "DIAMOND DUST! SHINY LIKE YOU!",
      "FROZEN IN TIME? NO, YOU'RE TIMELESS!",
      "ICE KING/QUEEN VIBES!",
      "COLD HANDS, WARM HEART OF GOLD!",
      "NOTHING CAN FREEZE YOUR GRIND!",
      "BREAK THE ICE! YOU'RE A STAR!",
      "CRYSTAL CLEAR VISION!",
      "SNOW GLOBE AESTHETIC!",
      "ARCTIC EXPLORER ENERGY!",
      "YOU'RE COOLER THAN LIQUID NITROGEN!",
      "FROST BITE? NAH, LOVE BITE FROM NATURE!",
      "SOLID!",
      "ICE COLD PLAYA!"
    ],
    RAIN: [
      "MAKE IT RAIN SUCCESS!",
      "LIQUID SUNSHINE! BLESSINGS!",
      "IMMACULATE DRIP!",
      "CLEANSING THE WORLD FOR YOU!",
      "PUDDLES ARE JUST MIRRORS FOR YOUR FACE!",
      "GROWTH MINDSET WEATHER!",
      "STORMING THE CASTLE!",
      "RAINBOW HUNTING! POT OF GOLD IS YOU!",
      "WET WEATHER, DRY HUMOR, PERFECT!",
      "SKY IS CRYING TEARS OF JOY SEEING YOU!",
      "SHOWERING YOU WITH LOVE!",
      "FLOW STATE!",
      "DROP IT LIKE IT'S HOT!",
      "HYDRO HOMIE!",
      "SPLASHING!"
    ],
    STORM: [
      "ELECTRIC ENERGY! JUST LIKE YOU!",
      "POWER OVERWHELMING!",
      "THUNDER IS APPLAUSE FOR YOUR EXISTENCE!",
      "STRIKING! STUNNING! SHOCKING!",
      "YOU ARE THE STORM!",
      "CHAOS COORDINATOR!",
      "HIGH VOLTAGE PERFORMANCE!",
      "LIGHTNING REFLEXES!",
      "BOOM! THERE GOES THE DYNAMITE!",
      "COMMANDING PRESENCE!",
      "SKY FIREWORKS!",
      "DRAMATIC ENTRANCE!",
      "UNSTOPPABLE FORCE!",
      "RUMBLE YOUNG MAN RUMBLE!",
      "GOD TIER WEATHER EFFECTS!"
    ],
    SNOW: [
      "PURE AS DRIVEN SNOW! THAT'S YOU!",
      "WALKING IN A WINTER WONDERLAND!",
      "FRESH POWDER! FRESH START!",
      "THE WORLD IS YOUR CANVAS!",
      "SNOW ANGEL! LITERALLY YOU!",
      "FROSTY THE GOAT!",
      "COOL AS ICE!",
      "WHITE GOLD!",
      "MAGICAL ATMOSPHERE!",
      "LET IT SNOW! LET YOU GLOW!",
      "SKI RESORT VIBES!",
      "COZY SEASON CHAMPION!",
      "FLAKE IT 'TIL YOU MAKE IT!",
      "BLIZZARD WIZARD!",
      "CHILLIN'!"
    ],
    NICE: [
      "PERFECT DAY FOR A PERFECT HUMAN!",
      "LITERALLY PARADISE! YOU DESERVE IT!",
      "GOD TIER WEATHER!",
      "MAIN CHARACTER ENERGY TODAY!",
      "SUNNY WITH A CHANCE OF WINNING!",
      "BLUE SKIES, GREEN LIGHTS!",
      "OPTIMAL VIBES!",
      "10/10 WOULD RECOMMEND (YOU)!",
      "BLESSED AND HIGHLY FAVORED!",
      "WALKING ON SUNSHINE!",
      "TOP TIER DAY!",
      "A MASTERPIECE PAINTED FOR YOU!",
      "GOOD MOOD ACTIVATED!",
      "THE UNIVERSE LOVES YOU!",
      "PURE BLISS!"
    ],
    DEFAULT: [
      "KILLING IT!",
      "LOOKING GOOD!",
      "DOMINATE!",
      "BIG W!",
      "LEGENDARY!",
      "GO GET 'EM!",
      "BOSS MOVES ONLY!",
      "YOU DROPPED THIS 👑!",
      "UNSTOPPABLE!",
      "ICONIC!",
      "BUILT DIFFERENT!",
      "HIM/HER!",
      "THE GOAT!",
      "KEEP SHINING!",
      "LOVE TO SEE IT!"
    ]
  },
  PROFESSIONAL: {
    EXTREME_HEAT: [
      "Advisory: Extreme heat event in progress.",
      "Safety Protocol: Seek shade and hydration.",
      "Solar radiation levels exceed nominal parameters.",
      "Thermal hazard detected.",
      "Core body temperature regulation advised.",
      "Surface temperatures dangerous for prolonged exposure.",
      "Heat index: Critical.",
      "UV Exposure: Maximum.",
      "Equipment overheating risk: High.",
      "Environment unsuitable for biological entities.",
      "Thermal throttling imminent.",
      "Caution: Heat stroke probability elevated.",
      "Atmospheric conditions: Hostile.",
      "Status: Excessive thermal load.",
      "Please remain indoors."
    ],
    HEAT: [
      "Temperature above regional average.",
      "Conditions: Warm.",
      "Perspiration likely.",
      "Hydration recommended.",
      "Solar output: Moderate to High.",
      "Thermal comfort: Reduced.",
      "A/C systems recommended.",
      "Summer conditions active.",
      "Heat detected.",
      "Ambient temperature: Elevated.",
      "Short sleeves appropriate.",
      "Activity level: Monitor for fatigue.",
      "Weather pattern: Stable heat.",
      "Sun block advised.",
      "Observation: It is warm."
    ],
    COLD: [
      "Temperature below nominal comfort levels.",
      "Thermal retention clothing advised.",
      "Conditions: Cool.",
      "Atmosphere: Crisp.",
      "Heating systems active.",
      "Mild cold stress detected.",
      "Precipitation unlikely but possible.",
      "Seasonal norm: Autumn/Winter.",
      "Ambient temperature: Low.",
      "Wind chill factor: Present.",
      "Exposure limit: Moderate.",
      "Status: Chilly.",
      "Observation: Temperature dropping.",
      "Insulation recommended.",
      "Sub-optimal thermal environment."
    ],
    FREEZING: [
      "Alert: Freezing point reached.",
      "Hazard: Ice formation on surfaces.",
      "Hypothermia risk: Elevated.",
      "Cryogenic conditions detected.",
      "Water state: Solid.",
      "Thermal protection required.",
      "Frostbite warning in effect.",
      "Conditions: Hazardous.",
      "Transport delay probability: High.",
      "Pipe bursting risk: Moderate.",
      "Ambient temperature: Critical low.",
      "Biological function slow-down.",
      "Status: Freezing.",
      "Winter weather event.",
      "Caution advised on walkways."
    ],
    RAIN: [
      "Precipitation event active.",
      "Liquid water falling.",
      "Humidity: 100%.",
      "Visibility: Reduced.",
      "Traction: Compromised.",
      "Umbrella/Rain gear suggested.",
      "Accumulation: Monitoring.",
      "Hydroplaning risk: Moderate.",
      "Atmospheric pressure: Low.",
      "Conditions: Wet.",
      "Cloud cover: Total.",
      "Status: Raining.",
      "Observation: Water cycle in progress.",
      "Outdoor activities discouraged.",
      "Surface friction reduced."
    ],
    STORM: [
      "Severe Weather Alert.",
      "Barometric pressure dropping rapidly.",
      "Electrical discharge detected.",
      "High wind velocity measured.",
      "Structural integrity risk: Low to Moderate.",
      "Precipitation: Heavy.",
      "Thunderstorm activity.",
      "Safety Protocol: Seek shelter immediately.",
      "Flight delays expected.",
      "Power fluctuation possible.",
      "Conditions: Turbulent.",
      "Status: Storming.",
      "Atmospheric instability.",
      "Gale force winds.",
      "Hazardous environment."
    ],
    SNOW: [
      "Solid precipitation detected.",
      "Crystalline water structure.",
      "Accumulation rates varying.",
      "Travel advisory in effect.",
      "Road conditions: Slick.",
      "Visibility: Poor.",
      "Snowfall active.",
      "Temperature: Below freezing.",
      "Winter maintenance required.",
      "Status: Snowing.",
      "Landscape albedo: High.",
      "Cold weather protocol active.",
      "Ice potential.",
      "Conditions: Wintry.",
      "Monitoring snowfall depth."
    ],
    NICE: [
      "Conditions: Optimal.",
      "Visibility: Unlimited.",
      "Atmospheric stability: High.",
      "Temperature: Nominal.",
      "Comfort index: Maximum.",
      "UV Index: Moderate.",
      "Precipitation: None.",
      "Wind: Light variable.",
      "Status: Clear.",
      "Recommendation: Outdoor activity.",
      "Bio-rhythm favorable.",
      "Sky condition: Clear.",
      "Standard operating parameters.",
      "Environment: Pleasant.",
      "No hazards detected."
    ],
    DEFAULT: [
      "System Online.",
      "Sensors active.",
      "Monitoring atmospheric conditions.",
      "Awaiting input.",
      "Data stream nominal.",
      "Status: Operational.",
      "Weather analysis complete.",
      "Update pending.",
      "No significant anomalies.",
      "Standard variance.",
      "Log entry created.",
      "Metrics stable.",
      "Calibrating.",
      "Scanning sector.",
      "Ready."
    ]
  }
};