// app/market/lib/nfl_data.ts

export interface Player {
  name: string;
  team: string;
  position: string;
  era: string;
  history: string;
  accentColor: string;
  searchQuery?: string;
}

export const NFL_PLAYERS: Player[] = [
  // ====================== ZENITH (The GOAT - 1 of 5) ======================
  { 
    name: 'Tom Brady', 
    team: 'Patriots/Bucs', 
    position: 'QB', 
    era: '2000-2022', 
    history: '7x Super Bowl Champion. The undisputed GOAT. Only 5 of these cards exist.', 
    accentColor: '#002244',
    searchQuery: 'Tom Brady screaming super bowl trophy'
  },

  // ====================== ULTRA (Immortals) ======================
  { name: 'Jerry Rice', team: '49ers', position: 'WR', era: '1985-2004', history: 'The greatest WR of all time. 22,895 yards.', accentColor: '#AA0000' },
  { name: 'Jim Brown', team: 'Browns', position: 'RB', era: '1957-1965', history: 'Averaged 104.3 yards per game. Unstoppable.', accentColor: '#311D00' },
  { name: 'Lawrence Taylor', team: 'Giants', position: 'LB', era: '1981-1993', history: 'Changed the way defense is played forever.', accentColor: '#001E62' },
  { name: 'Joe Montana', team: '49ers', position: 'QB', era: '1979-1994', history: 'Joe Cool. 4-0 in Super Bowls.', accentColor: '#B3995D' },
  { name: 'Walter Payton', team: 'Bears', position: 'RB', era: '1975-1987', history: 'Sweetness. 16,726 rushing yards.', accentColor: '#0B162A' },
  { name: 'Peyton Manning', team: 'Colts', position: 'QB', era: '1998-2015', history: '5x MVP. The Sheriff.', accentColor: '#002C5F' },
  { name: 'Reggie White', team: 'Eagles/Packers', position: 'DE', era: '1985-2000', history: 'The Minister of Defense. 198 sacks.', accentColor: '#004C54' },
  { name: 'Barry Sanders', team: 'Lions', position: 'RB', era: '1989-1998', history: 'Most elusive runner in history.', accentColor: '#0076B6' },
  { name: 'Ray Lewis', team: 'Ravens', position: 'LB', era: '1996-2012', history: 'The ultimate leader. 2x Super Bowl Champ.', accentColor: '#241773' },
  { name: 'Deion Sanders', team: 'Cowboys/Falcons', position: 'CB', era: '1989-2005', history: 'Prime Time. Scored 6 different ways.', accentColor: '#041E42' },
  { name: 'Patrick Mahomes', team: 'Chiefs', position: 'QB', era: '2017-Present', history: 'The modern standard. Magic arm.', accentColor: '#E31837' },
  { name: 'Dick Butkus', team: 'Bears', position: 'LB', era: '1965-1973', history: 'The most feared tackler ever.', accentColor: '#0B162A' },
  { name: 'Johnny Unitas', team: 'Colts', position: 'QB', era: '1956-1973', history: 'The Golden Arm. Invented the 2-minute drill.', accentColor: '#002C5F' },
  { name: 'Don Hutson', team: 'Packers', position: 'WR', era: '1935-1945', history: 'Invented the modern receiver position.', accentColor: '#203731' },

  // ====================== SUPER RARE (Hall of Famers) ======================
  { name: 'Aaron Rodgers', team: 'Packers', position: 'QB', era: '2005-Present', history: '4x MVP. Most talented arm ever.', accentColor: '#203731' },
  { name: 'Randy Moss', team: 'Vikings', position: 'WR', era: '1998-2012', history: 'The Freak. 23 TDs in one season.', accentColor: '#4F2683' },
  { name: 'Brett Favre', team: 'Packers', position: 'QB', era: '1991-2010', history: 'The Gunslinger. Iron Man.', accentColor: '#203731' },
  { name: 'Dan Marino', team: 'Dolphins', position: 'QB', era: '1983-1999', history: 'Quickest release in history.', accentColor: '#008E97' },
  { name: 'Emmitt Smith', team: 'Cowboys', position: 'RB', era: '1990-2004', history: 'All-time rushing leader (18,355).', accentColor: '#041E42' },
  { name: 'Calvin Johnson', team: 'Lions', position: 'WR', era: '2007-2015', history: 'Megatron. Uncoverable.', accentColor: '#0076B6' },
  { name: 'LaDainian Tomlinson', team: 'Chargers', position: 'RB', era: '2001-2011', history: '31 touchdowns in one season.', accentColor: '#0080C6' },
  { name: 'Ed Reed', team: 'Ravens', position: 'S', era: '2002-2013', history: 'The Ballhawk. 64 interceptions.', accentColor: '#241773' },
  { name: 'Troy Polamalu', team: 'Steelers', position: 'S', era: '2003-2014', history: 'Plays anywhere and everywhere.', accentColor: '#FFB612' },
  { name: 'Aaron Donald', team: 'Rams', position: 'DT', era: '2014-2023', history: '3x DPOY. Wrecking ball.', accentColor: '#003594' },
  { name: 'J.J. Watt', team: 'Texans', position: 'DE', era: '2011-2022', history: '3x DPOY. Swat commander.', accentColor: '#03202F' },
  { name: 'Rob Gronkowski', team: 'Patriots', position: 'TE', era: '2010-2021', history: 'Most dominant TE ever.', accentColor: '#002244' },
  { name: 'Terrell Owens', team: '49ers/Eagles', position: 'WR', era: '1996-2010', history: 'Get your popcorn ready.', accentColor: '#AA0000' },
  { name: 'John Elway', team: 'Broncos', position: 'QB', era: '1983-1998', history: 'The Drive. Helicopter spin.', accentColor: '#FB4F14' },
  { name: 'Ronnie Lott', team: '49ers', position: 'S', era: '1981-1994', history: 'Amputated a finger to keep playing.', accentColor: '#AA0000' },
  { name: 'Bruce Smith', team: 'Bills', position: 'DE', era: '1985-2003', history: 'All-time sack leader (200).', accentColor: '#00338D' },
  { name: 'Marshall Faulk', team: 'Rams', position: 'RB', era: '1994-2005', history: 'Greatest Show on Turf.', accentColor: '#003594' },
  { name: 'Eric Dickerson', team: 'Rams', position: 'RB', era: '1983-1993', history: '2,105 yards in a single season.', accentColor: '#003594' },
  { name: 'Deacon Jones', team: 'Rams', position: 'DE', era: '1961-1974', history: 'Coined the term "Sack".', accentColor: '#003594' },
  { name: 'Rod Woodson', team: 'Steelers', position: 'CB', era: '1987-2003', history: 'Most INT returns for TDs.', accentColor: '#FFB612' },
  { name: 'Tony Gonzalez', team: 'Chiefs', position: 'TE', era: '1997-2013', history: 'Reinvented the TE position.', accentColor: '#E31837' },
  { name: 'Larry Fitzgerald', team: 'Cardinals', position: 'WR', era: '2004-2020', history: 'More tackles than drops.', accentColor: '#97233F' },
  { name: 'Anthony Munoz', team: 'Bengals', position: 'OT', era: '1980-1992', history: 'The gold standard for linemen.', accentColor: '#FB4F14' },
  { name: 'Jonathan Ogden', team: 'Ravens', position: 'OT', era: '1996-2007', history: 'First ever Ravens draft pick.', accentColor: '#241773' },
  { name: 'Mean Joe Greene', team: 'Steelers', position: 'DT', era: '1969-1981', history: 'The Steel Curtain anchor.', accentColor: '#FFB612' },

  // ====================== RARE (Modern Stars / Cult Heroes) ======================
  { name: 'Bo Jackson', team: 'Raiders', position: 'RB', era: '1987-1990', history: 'The greatest athlete who ever lived.', accentColor: '#000000' },
  { name: 'Sean Taylor', team: 'Redskins', position: 'S', era: '2004-2007', history: 'The hardest hitter ever.', accentColor: '#773141' },
  { name: 'Michael Vick', team: 'Falcons', position: 'QB', era: '2001-2015', history: 'Changed the QB position forever.', accentColor: '#a71930' },
  { name: 'Marshawn Lynch', team: 'Seahawks', position: 'RB', era: '2007-2019', history: 'Beast Mode.', accentColor: '#69BE28' },
  { name: 'Travis Kelce', team: 'Chiefs', position: 'TE', era: '2013-Present', history: 'Always open.', accentColor: '#E31837' },
  { name: 'Von Miller', team: 'Broncos', position: 'LB', era: '2011-Present', history: 'Super Bowl 50 MVP.', accentColor: '#FB4F14' },
  { name: 'Julio Jones', team: 'Falcons', position: 'WR', era: '2011-Present', history: 'Physically dominant.', accentColor: '#a71930' },
  { name: 'Adrian Peterson', team: 'Vikings', position: 'RB', era: '2007-2021', history: 'All Day. 296 yards in one game.', accentColor: '#4F2683' },
  { name: 'Luke Kuechly', team: 'Panthers', position: 'LB', era: '2012-2019', history: 'Defensive mastermind.', accentColor: '#0085CA' },
  { name: 'Darrelle Revis', team: 'Jets', position: 'CB', era: '2007-2017', history: 'Revis Island.', accentColor: '#125740' },
  { name: 'Richard Sherman', team: 'Seahawks', position: 'CB', era: '2011-2021', history: 'Legion of Boom.', accentColor: '#69BE28' },
  { name: 'Kam Chancellor', team: 'Seahawks', position: 'S', era: '2010-2017', history: 'Bam Bam.', accentColor: '#69BE28' },
  { name: 'Earl Thomas', team: 'Seahawks', position: 'S', era: '2010-2019', history: 'Range for days.', accentColor: '#69BE28' },
  { name: 'Charles Woodson', team: 'Raiders/Packers', position: 'CB', era: '1998-2015', history: 'Only defensive Heisman winner.', accentColor: '#000000' },
  { name: 'Champ Bailey', team: 'Broncos', position: 'CB', era: '1999-2013', history: 'Shutdown corner.', accentColor: '#FB4F14' },
  { name: 'Tyreek Hill', team: 'Chiefs/Dolphins', position: 'WR', era: '2016-Present', history: 'The Cheetah.', accentColor: '#008E97' },
  { name: 'Derrick Henry', team: 'Titans', position: 'RB', era: '2016-Present', history: 'King Henry. 2K Club.', accentColor: '#4B92DB' },
  { name: 'Christian McCaffrey', team: '49ers', position: 'RB', era: '2017-Present', history: 'Run CMC.', accentColor: '#AA0000' },
  { name: 'T.J. Watt', team: 'Steelers', position: 'LB', era: '2017-Present', history: 'Sack artist.', accentColor: '#FFB612' },
  { name: 'Myles Garrett', team: 'Browns', position: 'DE', era: '2017-Present', history: 'Physical specimen.', accentColor: '#311D00' },
  { name: 'Khalil Mack', team: 'Bears', position: 'LB', era: '2014-Present', history: 'Defensive wrecking ball.', accentColor: '#0B162A' },
  { name: 'Davante Adams', team: 'Packers/Raiders', position: 'WR', era: '2014-Present', history: 'Best route runner.', accentColor: '#000000' },
  { name: 'Justin Jefferson', team: 'Vikings', position: 'WR', era: '2020-Present', history: 'The Griddy.', accentColor: '#4F2683' },
  { name: 'Ja\'Marr Chase', team: 'Bengals', position: 'WR', era: '2021-Present', history: 'Explosive playmaker.', accentColor: '#FB4F14' },
  { name: 'Cooper Kupp', team: 'Rams', position: 'WR', era: '2017-Present', history: 'Triple Crown winner.', accentColor: '#003594' },
  { name: 'Antonio Brown', team: 'Steelers', position: 'WR', era: '2010-2021', history: 'Dominant prime.', accentColor: '#FFB612' },
  { name: 'Jason Witten', team: 'Cowboys', position: 'TE', era: '2003-2020', history: 'Mr. Reliable.', accentColor: '#041E42' },
  { name: 'Antonio Gates', team: 'Chargers', position: 'TE', era: '2003-2018', history: 'Basketball background.', accentColor: '#0080C6' },
  { name: 'Shannon Sharpe', team: 'Broncos', position: 'TE', era: '1990-2003', history: 'Hall of Fame talker.', accentColor: '#FB4F14' },
  { name: 'Brian Dawkins', team: 'Eagles', position: 'S', era: '1996-2011', history: 'Weapon X.', accentColor: '#004C54' },
  { name: 'Brian Urlacher', team: 'Bears', position: 'LB', era: '2000-2012', history: 'Middle linebacker standard.', accentColor: '#0B162A' },
  { name: 'Junior Seau', team: 'Chargers', position: 'LB', era: '1990-2009', history: 'Passion for the game.', accentColor: '#0080C6' },
  { name: 'Patrick Willis', team: '49ers', position: 'LB', era: '2007-2014', history: 'Short but dominant career.', accentColor: '#AA0000' },
  { name: 'Derrick Brooks', team: 'Bucs', position: 'LB', era: '1995-2008', history: 'Tampa 2 legend.', accentColor: '#D50A0A' },
  { name: 'Julius Peppers', team: 'Panthers', position: 'DE', era: '2002-2018', history: 'Freak of nature.', accentColor: '#0085CA' },

  // ====================== UNCOMMON (Stars & Reliable Greats) ======================
  { name: 'Frank Gore', team: '49ers', position: 'RB', era: '2005-2020', history: 'The Inconvenient Truth.', accentColor: '#AA0000' },
  { name: 'Philip Rivers', team: 'Chargers', position: 'QB', era: '2004-2020', history: 'Iron man QB.', accentColor: '#0080C6' },
  { name: 'Ben Roethlisberger', team: 'Steelers', position: 'QB', era: '2004-2021', history: 'Big Ben.', accentColor: '#FFB612' },
  { name: 'Eli Manning', team: 'Giants', position: 'QB', era: '2004-2019', history: '2x Super Bowl MVP.', accentColor: '#001E62' },
  { name: 'Matt Ryan', team: 'Falcons', position: 'QB', era: '2008-2022', history: 'Matty Ice.', accentColor: '#a71930' },
  { name: 'Russell Wilson', team: 'Seahawks', position: 'QB', era: '2012-Present', history: 'Let Russ Cook.', accentColor: '#69BE28' },
  { name: 'Cam Newton', team: 'Panthers', position: 'QB', era: '2011-2021', history: 'Superman.', accentColor: '#0085CA' },
  { name: 'Lamar Jackson', team: 'Ravens', position: 'QB', era: '2018-Present', history: 'Electric playmaker.', accentColor: '#241773' },
  { name: 'Josh Allen', team: 'Bills', position: 'QB', era: '2018-Present', history: 'Cannon arm.', accentColor: '#00338D' },
  { name: 'Joe Burrow', team: 'Bengals', position: 'QB', era: '2020-Present', history: 'Joe Shiesty.', accentColor: '#FB4F14' },
  { name: 'Justin Herbert', team: 'Chargers', position: 'QB', era: '2020-Present', history: 'Rocket arm.', accentColor: '#0080C6' },
  { name: 'Matthew Stafford', team: 'Rams', position: 'QB', era: '2009-Present', history: 'Toughness personified.', accentColor: '#003594' },
  { name: 'Le\'Veon Bell', team: 'Steelers', position: 'RB', era: '2013-2021', history: 'Patient runner.', accentColor: '#FFB612' },
  { name: 'Todd Gurley', team: 'Rams', position: 'RB', era: '2015-2020', history: 'Offensive player of the year.', accentColor: '#003594' },
  { name: 'Alvin Kamara', team: 'Saints', position: 'RB', era: '2017-Present', history: 'Balance king.', accentColor: '#D3BC8D' },
  { name: 'Nick Chubb', team: 'Browns', position: 'RB', era: '2018-Present', history: 'Pure power.', accentColor: '#311D00' },
  { name: 'Saquon Barkley', team: 'Giants/Eagles', position: 'RB', era: '2018-Present', history: 'Generational talent.', accentColor: '#001E62' },
  { name: 'Ezekiel Elliott', team: 'Cowboys', position: 'RB', era: '2016-Present', history: 'Feed Zeke.', accentColor: '#041E42' },
  { name: 'Steve Young', team: '49ers', position: 'QB', era: '1985-1999', history: 'Lefty legend.', accentColor: '#AA0000' },
  { name: 'Kurt Warner', team: 'Rams', position: 'QB', era: '1998-2009', history: 'Grocery bagger to MVP.', accentColor: '#003594' },
  { name: 'Troy Aikman', team: 'Cowboys', position: 'QB', era: '1989-2000', history: '3x Champion.', accentColor: '#041E42' },
  { name: 'Warren Moon', team: 'Oilers', position: 'QB', era: '1978-2000', history: 'CFL to NFL legend.', accentColor: '#4B92DB' },
  { name: 'Fran Tarkenton', team: 'Vikings', position: 'QB', era: '1961-1978', history: 'Original scrambler.', accentColor: '#4F2683' },
  { name: 'Terry Bradshaw', team: 'Steelers', position: 'QB', era: '1970-1983', history: 'Blonde Bomber.', accentColor: '#FFB612' },
  { name: 'Joe Namath', team: 'Jets', position: 'QB', era: '1965-1977', history: 'Broadway Joe.', accentColor: '#125740' },
  { name: 'Roger Staubach', team: 'Cowboys', position: 'QB', era: '1969-1979', history: 'Captain America.', accentColor: '#041E42' },
  { name: 'Ken Stabler', team: 'Raiders', position: 'QB', era: '1970-1984', history: 'The Snake.', accentColor: '#000000' },
  { name: 'Larry Csonka', team: 'Dolphins', position: 'FB', era: '1968-1979', history: 'Perfect season.', accentColor: '#008E97' },
  { name: 'Franco Harris', team: 'Steelers', position: 'RB', era: '1972-1984', history: 'Immaculate Reception.', accentColor: '#FFB612' },
  { name: 'Earl Campbell', team: 'Oilers', position: 'RB', era: '1978-1985', history: 'The Tyler Rose.', accentColor: '#4B92DB' },
  { name: 'Gale Sayers', team: 'Bears', position: 'RB', era: '1965-1971', history: 'Kansas Comet.', accentColor: '#0B162A' },
  { name: 'O.J. Simpson', team: 'Bills', position: 'RB', era: '1969-1979', history: 'First to 2000 yards.', accentColor: '#00338D' },
  { name: 'Marcus Allen', team: 'Raiders', position: 'RB', era: '1982-1997', history: 'Super Bowl MVP.', accentColor: '#000000' },
  { name: 'Thurman Thomas', team: 'Bills', position: 'RB', era: '1988-2000', history: 'Dual threat.', accentColor: '#00338D' },
  { name: 'Jerome Bettis', team: 'Steelers', position: 'RB', era: '1993-2005', history: 'The Bus.', accentColor: '#FFB612' },
  { name: 'Curtis Martin', team: 'Jets', position: 'RB', era: '1995-2005', history: 'Consistency defined.', accentColor: '#125740' },
  { name: 'C.J. Stroud', team: 'Texans', position: 'QB', era: '2023-Present', history: 'Rookie sensation.', accentColor: '#03202F' },
  { name: 'Josh Jacobs', team: 'Raiders', position: 'RB', era: '2019-Present', history: 'Rushing champ.', accentColor: '#000000' },
  { name: 'DeAndre Hopkins', team: 'Texans/Cards', position: 'WR', era: '2013-Present', history: 'Best hands.', accentColor: '#03202F' },
  { name: 'Odell Beckham Jr.', team: 'Giants', position: 'WR', era: '2014-Present', history: 'The Catch.', accentColor: '#001E62' },

  // ====================== COMMON (Solid Players & Rookies) ======================
  { name: 'Shaun Alexander', team: 'Seahawks', position: 'RB', era: '2000-2008', history: 'MVP season.', accentColor: '#69BE28' },
  { name: 'Priest Holmes', team: 'Chiefs', position: 'RB', era: '1997-2007', history: 'Touchdown machine.', accentColor: '#E31837' },
  { name: 'Clinton Portis', team: 'Redskins', position: 'RB', era: '2002-2010', history: 'Costume king.', accentColor: '#773141' },
  { name: 'Edgerrin James', team: 'Colts', position: 'RB', era: '1999-2009', history: 'The Edge.', accentColor: '#002C5F' },
  { name: 'Fred Taylor', team: 'Jaguars', position: 'RB', era: '1998-2010', history: 'Fragile Fred (Underrated).', accentColor: '#006778' },
  { name: 'Corey Dillon', team: 'Bengals', position: 'RB', era: '1997-2006', history: 'Power runner.', accentColor: '#FB4F14' },
  { name: 'Steven Jackson', team: 'Rams', position: 'RB', era: '2004-2015', history: 'Bell cow back.', accentColor: '#003594' },
  { name: 'Matt Forte', team: 'Bears', position: 'RB', era: '2008-2017', history: 'Catching back.', accentColor: '#0B162A' },
  { name: 'Jamaal Charles', team: 'Chiefs', position: 'RB', era: '2008-2018', history: 'Highest YPC average.', accentColor: '#E31837' },
  { name: 'Chris Johnson', team: 'Titans', position: 'RB', era: '2008-2017', history: 'CJ2K.', accentColor: '#4B92DB' },
  { name: 'Maurice Jones-Drew', team: 'Jaguars', position: 'RB', era: '2006-2014', history: 'Pocket Hercules.', accentColor: '#006778' },
  { name: 'Arian Foster', team: 'Texans', position: 'RB', era: '2009-2016', history: 'Namaste.', accentColor: '#03202F' },
  { name: 'Ray Rice', team: 'Ravens', position: 'RB', era: '2008-2013', history: 'Hey Diddle Diddle.', accentColor: '#241773' },
  { name: 'DeMarco Murray', team: 'Cowboys', position: 'RB', era: '2011-2017', history: 'League leading rusher.', accentColor: '#041E42' },
  { name: 'Devonta Freeman', team: 'Falcons', position: 'RB', era: '2014-2021', history: 'Super Bowl runner.', accentColor: '#a71930' },
  { name: 'Melvin Gordon', team: 'Chargers', position: 'RB', era: '2015-Present', history: 'Touchdown maker.', accentColor: '#0080C6' },
  { name: 'Kareem Hunt', team: 'Chiefs/Browns', position: 'RB', era: '2017-Present', history: 'Hurdle master.', accentColor: '#E31837' },
  { name: 'Joe Mixon', team: 'Bengals', position: 'RB', era: '2017-Present', history: 'Workhorse.', accentColor: '#FB4F14' },
  { name: 'Aaron Jones', team: 'Packers', position: 'RB', era: '2017-Present', history: 'Showtyme.', accentColor: '#203731' },
  { name: 'Dalvin Cook', team: 'Vikings', position: 'RB', era: '2017-Present', history: 'The Chef.', accentColor: '#4F2683' },
  { name: 'Austin Ekeler', team: 'Chargers', position: 'RB', era: '2017-Present', history: 'Pound for pound strong.', accentColor: '#0080C6' },
  { name: 'Jonathan Taylor', team: 'Colts', position: 'RB', era: '2020-Present', history: 'Rushing title.', accentColor: '#002C5F' },
  { name: 'Najee Harris', team: 'Steelers', position: 'RB', era: '2021-Present', history: 'Power back.', accentColor: '#FFB612' },
  { name: 'Travis Etienne', team: 'Jaguars', position: 'RB', era: '2021-Present', history: 'Speedster.', accentColor: '#006778' },
  { name: 'Breece Hall', team: 'Jets', position: 'RB', era: '2022-Present', history: 'Young star.', accentColor: '#125740' },
  { name: 'Kenneth Walker III', team: 'Seahawks', position: 'RB', era: '2022-Present', history: 'K9.', accentColor: '#69BE28' },
  { name: 'Bijan Robinson', team: 'Falcons', position: 'RB', era: '2023-Present', history: 'Top prospect.', accentColor: '#a71930' },
  { name: 'Jahmyr Gibbs', team: 'Lions', position: 'RB', era: '2023-Present', history: 'Electric rookie.', accentColor: '#0076B6' },
  { name: 'Kyren Williams', team: 'Rams', position: 'RB', era: '2022-Present', history: 'Breakout star.', accentColor: '#003594' },
  { name: 'Raheem Mostert', team: 'Dolphins', position: 'RB', era: '2015-Present', history: 'TD machine.', accentColor: '#008E97' },
  { name: 'James Cook', team: 'Bills', position: 'RB', era: '2022-Present', history: 'Smooth runner.', accentColor: '#00338D' },
  { name: 'Isiah Pacheco', team: 'Chiefs', position: 'RB', era: '2022-Present', history: 'Angry runner.', accentColor: '#E31837' },
  { name: 'Rachaad White', team: 'Bucs', position: 'RB', era: '2022-Present', history: 'Dual threat.', accentColor: '#D50A0A' },
  { name: 'D\'Andre Swift', team: 'Eagles', position: 'RB', era: '2020-Present', history: 'Shifty.', accentColor: '#004C54' },
  { name: 'Tony Pollard', team: 'Cowboys', position: 'RB', era: '2019-Present', history: 'Explosive.', accentColor: '#041E42' },
  { name: 'Devin Hester', team: 'Bears', position: 'KR', era: '2006-2016', history: 'Ridiculous returner.', accentColor: '#0B162A' },
  { name: 'Adam Vinatieri', team: 'Patriots/Colts', position: 'K', era: '1996-2019', history: 'Clutch kicker.', accentColor: '#002244' },
  { name: 'Justin Tucker', team: 'Ravens', position: 'K', era: '2012-Present', history: 'Most accurate ever.', accentColor: '#241773' },
  { name: 'Sebastian Janikowski', team: 'Raiders', position: 'K', era: '2000-2018', history: 'Sea Bass.', accentColor: '#000000' },
  { name: 'Pat McAfee', team: 'Colts', position: 'P', era: '2009-2016', history: 'For the brand.', accentColor: '#002C5F' },
  { name: 'Chad Johnson', team: 'Bengals', position: 'WR', era: '2001-2011', history: 'Ochocinco.', accentColor: '#FB4F14' },
  { name: 'Wes Welker', team: 'Patriots', position: 'WR', era: '2004-2015', history: 'Slot machine.', accentColor: '#002244' },
  { name: 'Julian Edelman', team: 'Patriots', position: 'WR', era: '2009-2020', history: 'Playoff clutch.', accentColor: '#002244' },
  { name: 'Hines Ward', team: 'Steelers', position: 'WR', era: '1998-2011', history: 'Blocking WR.', accentColor: '#FFB612' },
  { name: 'Anquan Boldin', team: 'Cardinals', position: 'WR', era: '2003-2016', history: 'So strong.', accentColor: '#97233F' },
  { name: 'Steve Smith Sr.', team: 'Panthers', position: 'WR', era: '2001-2016', history: 'Ice up son.', accentColor: '#0085CA' },
  { name: 'Reggie Wayne', team: 'Colts', position: 'WR', era: '2001-2014', history: 'Consistent great.', accentColor: '#002C5F' },
  { name: 'Torry Holt', team: 'Rams', position: 'WR', era: '1999-2009', history: 'Big Game.', accentColor: '#003594' },
  { name: 'Isaac Bruce', team: 'Rams', position: 'WR', era: '1994-2009', history: 'Rev.', accentColor: '#003594' },
  { name: 'Andre Johnson', team: 'Texans', position: 'WR', era: '2003-2016', history: 'Quiet storm.', accentColor: '#03202F' },
  { name: 'Demaryius Thomas', team: 'Broncos', position: 'WR', era: '2010-2019', history: 'Screen pass king.', accentColor: '#FB4F14' },
  { name: 'Dez Bryant', team: 'Cowboys', position: 'WR', era: '2010-2020', history: 'Throw up the X.', accentColor: '#041E42' },
  { name: 'Brandon Marshall', team: 'Bears/Jets', position: 'WR', era: '2006-2018', history: 'Physical beast.', accentColor: '#0B162A' },
  { name: 'Vincent Jackson', team: 'Chargers', position: 'WR', era: '2005-2016', history: 'Deep threat.', accentColor: '#0080C6' },
  { name: 'Roddy White', team: 'Falcons', position: 'WR', era: '2005-2015', history: 'Mr. Falcon.', accentColor: '#a71930' },
  { name: 'Greg Olsen', team: 'Panthers', position: 'TE', era: '2007-2020', history: 'Reliable hands.', accentColor: '#0085CA' },
  { name: 'Vernon Davis', team: '49ers', position: 'TE', era: '2006-2019', history: 'Athletic freak.', accentColor: '#AA0000' },
  { name: 'Jimmy Graham', team: 'Saints', position: 'TE', era: '2010-Present', history: 'Red zone target.', accentColor: '#D3BC8D' },
  { name: 'Jared Allen', team: 'Vikings', position: 'DE', era: '2004-2015', history: 'Calf roping.', accentColor: '#4F2683' },
  { name: 'DeMarcus Ware', team: 'Cowboys', position: 'LB', era: '2005-2016', history: 'Sack master.', accentColor: '#041E42' },
  { name: 'Robert Mathis', team: 'Colts', position: 'DE', era: '2003-2016', history: 'Strip sack king.', accentColor: '#002C5F' },
  { name: 'Dwight Freeney', team: 'Colts', position: 'DE', era: '2002-2017', history: 'Spin move.', accentColor: '#002C5F' },
  { name: 'Vince Wilfork', team: 'Patriots', position: 'DT', era: '2004-2016', history: 'Big Vince.', accentColor: '#002244' },
  { name: 'Haloti Ngata', team: 'Ravens', position: 'DT', era: '2006-2018', history: 'Immovable object.', accentColor: '#241773' },
  { name: 'Ndamukong Suh', team: 'Lions', position: 'DT', era: '2010-2022', history: 'Mean streak.', accentColor: '#0076B6' },
  { name: 'Geno Atkins', team: 'Bengals', position: 'DT', era: '2010-2020', history: 'Interior pressure.', accentColor: '#FB4F14' },
  { name: 'Fletcher Cox', team: 'Eagles', position: 'DT', era: '2012-2023', history: 'Eagles legend.', accentColor: '#004C54' },
  { name: 'Cameron Jordan', team: 'Saints', position: 'DE', era: '2011-Present', history: 'Consistent power.', accentColor: '#D3BC8D' },
  { name: 'Chandler Jones', team: 'Cardinals', position: 'LB', era: '2012-2023', history: 'Sack production.', accentColor: '#97233F' },
  { name: 'Bobby Wagner', team: 'Seahawks', position: 'LB', era: '2012-Present', history: 'Tackle machine.', accentColor: '#69BE28' },
  { name: 'Lavonte David', team: 'Bucs', position: 'LB', era: '2012-Present', history: 'Underrated star.', accentColor: '#D50A0A' },
  { name: 'Demario Davis', team: 'Saints', position: 'LB', era: '2012-Present', history: 'Late bloomer.', accentColor: '#D3BC8D' },
  { name: 'Fred Warner', team: '49ers', position: 'LB', era: '2018-Present', history: 'Coverage LB.', accentColor: '#AA0000' },
  { name: 'Stephon Gilmore', team: 'Patriots', position: 'CB', era: '2012-Present', history: 'Gilly Lock.', accentColor: '#002244' },
  { name: 'Jalen Ramsey', team: 'Jaguars/Rams', position: 'CB', era: '2016-Present', history: 'Trash talker.', accentColor: '#006778' },
  { name: 'Patrick Peterson', team: 'Cardinals', position: 'CB', era: '2011-Present', history: 'Athletic marvel.', accentColor: '#97233F' },
  { name: 'Xavien Howard', team: 'Dolphins', position: 'CB', era: '2016-Present', history: 'Ball hawk.', accentColor: '#008E97' },
  { name: 'Tre\'Davious White', team: 'Bills', position: 'CB', era: '2017-Present', history: 'Goalie Academy.', accentColor: '#00338D' },
  { name: 'Sauce Gardner', team: 'Jets', position: 'CB', era: '2022-Present', history: 'Lost in the Sauce.', accentColor: '#125740' },
  { name: 'Pat Surtain II', team: 'Broncos', position: 'CB', era: '2021-Present', history: 'Technician.', accentColor: '#FB4F14' },
  { name: 'Minkah Fitzpatrick', team: 'Steelers', position: 'S', era: '2018-Present', history: 'Playmaker.', accentColor: '#FFB612' },
  { name: 'Derwin James', team: 'Chargers', position: 'S', era: '2018-Present', history: 'Swiss army knife.', accentColor: '#0080C6' },
  { name: 'Budda Baker', team: 'Cardinals', position: 'S', era: '2017-Present', history: 'Missile.', accentColor: '#97233F' },
  { name: 'Tyrann Mathieu', team: 'Chiefs/Saints', position: 'S', era: '2013-Present', history: 'Honey Badger.', accentColor: '#E31837' },
  { name: 'Harrison Smith', team: 'Vikings', position: 'S', era: '2012-Present', history: 'The Hitman.', accentColor: '#4F2683' },
  { name: 'Justin Simmons', team: 'Broncos', position: 'S', era: '2016-Present', history: 'Ball production.', accentColor: '#FB4F14' },
  { name: 'Micah Parsons', team: 'Cowboys', position: 'LB', era: '2021-Present', history: 'Lion.', accentColor: '#041E42' },
  { name: 'Maxx Crosby', team: 'Raiders', position: 'DE', era: '2019-Present', history: 'The Condor.', accentColor: '#000000' },
  { name: 'Aidan Hutchinson', team: 'Lions', position: 'DE', era: '2022-Present', history: 'Motor.', accentColor: '#0076B6' },
  { name: 'Nick Bosa', team: '49ers', position: 'DE', era: '2019-Present', history: 'Technique.', accentColor: '#AA0000' },
  { name: 'Joey Bosa', team: 'Chargers', position: 'DE', era: '2016-Present', history: 'Big Bear.', accentColor: '#0080C6' },
  { name: 'Jeffery Simmons', team: 'Titans', position: 'DT', era: '2019-Present', history: 'Power.', accentColor: '#4B92DB' },
  { name: 'Quinnen Williams', team: 'Jets', position: 'DT', era: '2019-Present', history: 'Disruptor.', accentColor: '#125740' },
  { name: 'Dexter Lawrence', team: 'Giants', position: 'DT', era: '2019-Present', history: 'Sexy Dexy.', accentColor: '#001E62' },
  { name: 'Chris Jones', team: 'Chiefs', position: 'DT', era: '2016-Present', history: 'Closer.', accentColor: '#E31837' },
  { name: 'Trent Williams', team: '49ers', position: 'OT', era: '2010-Present', history: 'Silverback.', accentColor: '#AA0000' },
  { name: 'Jason Kelce', team: 'Eagles', position: 'C', era: '2011-2023', history: 'Underdog.', accentColor: '#004C54' },
  { name: 'Zack Martin', team: 'Cowboys', position: 'G', era: '2014-Present', history: 'Perfection.', accentColor: '#041E42' },
  { name: 'Lane Johnson', team: 'Eagles', position: 'OT', era: '2013-Present', history: 'Athletic tackle.', accentColor: '#004C54' },
  { name: 'Tyron Smith', team: 'Cowboys', position: 'OT', era: '2011-Present', history: 'All decade.', accentColor: '#041E42' },
  { name: 'Penei Sewell', team: 'Lions', position: 'OT', era: '2021-Present', history: 'Young king.', accentColor: '#0076B6' },
  { name: 'Creed Humphrey', team: 'Chiefs', position: 'C', era: '2021-Present', history: 'Lefty center.', accentColor: '#E31837' },
  { name: 'Joe Thomas', team: 'Browns', position: 'OT', era: '2007-2017', history: 'First ballot HOF.', accentColor: '#311D00' },
  { name: 'Andrew Whitworth', team: 'Rams', position: 'OT', era: '2006-2021', history: 'Ageless wonder.', accentColor: '#003594' },
  { name: 'Marshal Yanda', team: 'Ravens', position: 'G', era: '2007-2019', history: 'Grit.', accentColor: '#241773' },
  { name: 'Maurkice Pouncey', team: 'Steelers', position: 'C', era: '2010-2020', history: 'Leader.', accentColor: '#FFB612' }
];